OfficeDev/Office-Addin-Scripts

- packages/office-addin-dev-certs/src/install.ts
- packages/office-addin-dev-certs/test/test.ts
> quote powershell arguments that may contain a space

- packages/custom-functions-metadata-plugin/package-lock.json
- packages/custom-functions-metadata/package-lock.json
- packages/custom-functions-metadata/package.json
- packages/office-addin-cli/package-lock.json
- packages/office-addin-debugging/package-lock.json
- packages/office-addin-dev-certs/package-lock.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-manifest/package-lock.json
- packages/office-addin-manifest/package.json
- packages/office-addin-node-debugger/package-lock.json
- packages/office-addin-test-helpers/package-lock.json
- packages/office-addin-test-server/package-lock.json
Fixes #157 
fs is part of Node.js itself; there should not be a dependency in package.json.
> remove fs dependency

- packages/office-addin-debugging/src/start.ts
@GabeMedrash noticed this as part of #156.
> fix missing await

- packages/custom-functions-metadata-plugin/package-lock.json
- packages/custom-functions-metadata-plugin/package.json
- packages/custom-functions-metadata/package-lock.json
- packages/custom-functions-metadata/package.json
- packages/eslint-config-office-addins/package.json
- packages/office-addin-cli/package-lock.json
- packages/office-addin-cli/package.json
- packages/office-addin-debugging/package-lock.json
- packages/office-addin-debugging/package.json
- packages/office-addin-dev-certs/package-lock.json
- packages/office-addin-dev-certs/package.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-dev-settings/package.json
- packages/office-addin-lint/package-lock.json
- packages/office-addin-lint/package.json
- packages/office-addin-manifest/package-lock.json
- packages/office-addin-manifest/package.json
- packages/office-addin-node-debugger/package-lock.json
- packages/office-addin-node-debugger/package.json
- packages/office-addin-test-helpers/package-lock.json
- packages/office-addin-test-helpers/package.json
- packages/office-addin-test-server/package-lock.json
- packages/office-addin-test-server/package.json
- packages/office-addin-test-server/src/cli.ts
- packages/office-addin-test-server/src/commands.ts
- packages/office-addin-test-server/src/testServer.ts
I'm splitting up pull request https://github.com/OfficeDev/Office-Addin-Scripts/pull/177 into several smaller pull requests. 
This one updates the typescript version for all packages to the latest, along with ts-node and tslint.
> Update typescript version

- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-dev-settings/package.json
fs-extra package should be a runtime dependency.
> fix office-addin-dev-settings dependencies

- packages/office-addin-lint/package-lock.json
- packages/office-addin-lint/package.json
> update typescript eslint version

- packages/office-addin-usage-data/src/defaults.ts
- packages/office-addin-usage-data/src/usageData.ts
- packages/office-addin-usage-data/test/test.ts
also add instrumentation key to default.ts
> Update event and error reporting to capture whether test data

- packages/office-addin-dev-settings/src/registry.ts
Fixes https://github.com/OfficeDev/Office-Addin-Scripts/issues/215.
Check whether the registry key/value exists when deleting it rather than relying on the error message.
The error message may not be in English and therefore cannot be relied upon to know whether the error
indicates that the registry key/value doesn't exist or another error occurred.
> fix registry key/value delete when doesn't exist

- packages/eslint-plugin-office-addins/README.md
- packages/eslint-plugin-office-addins/package-lock.json
- packages/eslint-plugin-office-addins/package.json
- packages/eslint-plugin-office-addins/src/main.ts
- packages/eslint-plugin-office-addins/tsconfig.json
This creates an eslint plugin for office-addins to use.  It has 3 configs which can be used.
"extended": [
"plugin:office-addins/recommended",
"plugin:office-addins/react",
"plugin:office-addins/reactnative"
]
> eslint plugin for office-addins

- packages/eslint-plugin-office-addins/package-lock.json
- packages/eslint-plugin-office-addins/package.json
Moving devDependencies to dependencies.
> moving dependencies

- package-lock.json
- We have numerous Component Governance Alert bugs opened against Office-Addin-Scripts.  Updating packages to address these issues
> Update packages to address Component Governance Alerts

- packages/office-addin-sso/package-lock.json
- packages/office-addin-sso/package.json
- packages/office-addin-sso/src/authRoute.ts
- packages/office-addin-sso/src/commands.ts
- packages/office-addin-sso/src/configure.ts
- packages/office-addin-sso/src/defaults.ts
- packages/office-addin-sso/src/server.ts
- packages/office-addin-sso/src/ssoDataSettings.ts
- packages/office-addin-sso/src/usagedata-helper.ts
- Note, I am running into problems when trying to add usage data for files that the SSO taskpane app imports.  Webpack fails to build with errors related to the applicationInsights package that office-addin-usage-data consumes
Sample data available at https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Ffb31a92f-824a-4de5-bf31-722222f81009%2FresourceGroups%2FOffice-Addin-Usage-Data%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2FOffice-Addin-Usage-Data/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA0suLS7Jz3UtS80rKeaqUcjJzM0sUTA1MACyyzNSi1IV8hJzUxVsbRWU8tPSMpNTdRNTUjLzdIuL85UUuAAtgoKQPQAAAA%253D%253D/timespan/P1D
> Add usage data for SSO configuration and server processes

- packages/office-addin-sso/package-lock.json
- packages/office-addin-sso/src/commands.ts
- packages/office-addin-sso/src/configure.ts
- packages/office-addin-sso/src/defaults.ts
- packages/office-addin-sso/src/scripts/azRestAddTenantOutlookReplyUrls.txt
This PR enables Outlook support for SSO by setting the Outlook reply url if it's not already set for the Outlook Add-in service principal
> Add code to set OWA reply url

- packages/office-addin-manifest/src/main.ts
> [office-addin-mainfest] update exports in main.ts

- package-lock.json
- package.json
- Updating the package fixes the test hangs we have seen recently
- Also addresses some Component Governance bugs we have
> Update lerna package to latest version

- package-lock.json
- packages/custom-functions-metadata-plugin/package-lock.json
- packages/custom-functions-metadata-plugin/package.json
- packages/custom-functions-metadata/package-lock.json
- packages/eslint-plugin-office-addins/package-lock.json
- packages/eslint-plugin-office-addins/package.json
- packages/office-addin-cli/package-lock.json
- packages/office-addin-cli/package.json
- packages/office-addin-debugging/package-lock.json
- packages/office-addin-debugging/package.json
- packages/office-addin-dev-certs/package-lock.json
- packages/office-addin-dev-certs/package.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-dev-settings/package.json
- packages/office-addin-lint/package-lock.json
- packages/office-addin-lint/package.json
- packages/office-addin-manifest/package-lock.json
- packages/office-addin-manifest/package.json
- packages/office-addin-node-debugger/package-lock.json
- packages/office-addin-sso/package-lock.json
- packages/office-addin-sso/package.json
- packages/office-addin-test-helpers/package-lock.json
- packages/office-addin-test-helpers/package.json
- packages/office-addin-test-server/package-lock.json
- packages/office-addin-test-server/package.json
- packages/office-addin-usage-data/package-lock.json
- packages/office-addin-usage-data/package.json
- But not all due to the fact that there are vulnerabilities in lerna, webpack and cpx, for which we have the latest versions already
> Addresses most Component Governance issues

- packages/office-addin-debugging/src/start.ts
- Only executes if OS is Windows 10
> Enable code to ensure Edge loopback is enabled

- packages/office-addin-sso/package-lock.json
- packages/office-addin-sso/package.json
- Using copyfiles instead of cpx is causing our built files to get copied to the wrong folder in the lib directory and breaking the configure process for sso
> Revert previous change from cpx to copyfiles due to breaking error

- package-lock.json
- packages/office-addin-sso/package-lock.json
- packages/office-addin-sso/package.json
- packages/office-addin-test-helpers/package-lock.json
- packages/office-addin-test-helpers/package.json
- packages/office-addin-test-server/package-lock.json
- packages/office-addin-test-server/package.json
- packages/office-addin-usage-data/package-lock.json
- packages/office-addin-usage-data/package.json
- This also contains an alternative for cpx, which is no longer activelu supported and has persistent vulnerabilties
> Update packages to address security vulnerabilities

- packages/office-addin-dev-settings/README.md
Added information about the webview switcher to the office-addin-dev-settings readme
> Add information about the webview switcher to readme

- packages/custom-functions-metadata-plugin/package-lock.json
- packages/custom-functions-metadata/package-lock.json
- packages/custom-functions-metadata/package.json
- This package isn't even being used so there is no need to have it in the project
> optimist package generates high vulnerabilities - removing

- package-lock.json
- package.json
- packages/custom-functions-metadata-plugin/package-lock.json
- packages/custom-functions-metadata-plugin/package.json
- packages/office-addin-usage-data/package-lock.json
- However lerna still has vulnerabilties even after updating to the latest version of the package
> Fix security vulnerabilities

- packages/office-addin-lint/.vscode/launch.json
- packages/office-addin-lint/package-lock.json
- packages/office-addin-lint/package.json
- packages/office-addin-lint/src/cli.ts
- packages/office-addin-lint/src/commands.ts
- packages/office-addin-lint/src/defaults.ts
- packages/office-addin-lint/src/lint.ts
> Putting office-addin-lint usage data changes in separate branch to make integration easier

- package-lock.json
- packages/office-addin-debugging/package-lock.json
- packages/office-addin-debugging/package.json
- packages/office-addin-dev-settings/.vscode/launch.json
- packages/office-addin-dev-settings/src/appType.ts
- packages/office-addin-dev-settings/src/cli.ts
- packages/office-addin-dev-settings/src/commands.ts
- packages/office-addin-dev-settings/src/main.ts
- packages/office-addin-dev-settings/src/sideload.ts
- packages/office-addin-dev-settings/test/unit-tests/test.ts
- packages/office-addin-lint/package-lock.json
- packages/office-addin-usage-data/package-lock.json
I used the sideload command with Office-Addin-TaskPane and found some improvements that could be made.
> sideload command tweaks

- .azure-devops/build-pipeline.yaml
- .azure-devops/steps/build.yaml
- .azure-devops/steps/cleanup.yaml
- .azure-devops/steps/npm-install.yaml
- .azure-devops/steps/run-tests.yaml
This will allow for making changes to the build pipeline using pull requests instead of directly editing the settings.
The Linux agent is specified as "ubuntu-latest" rather than "ubuntu-16.04". The latest is currently "ubuntu-18.04".
> Use yaml files for Azure DevOps pipeline 

- README.md
Just updating the README to have a quick and easy introduction to start out contributing to this project.
> Adding git quickstart section to README

- packages/office-addin-lint/package-lock.json
- packages/office-addin-sso/package-lock.json
I wanted to publish to the next dist-tag, but there were these lock file changes after running npm install.
> update package-lock.json files

- packages/office-addin-debugging/package-lock.json
- packages/office-addin-debugging/src/commands.ts
- packages/office-addin-debugging/src/port.ts
- packages/office-addin-debugging/src/start.ts
- packages/office-addin-debugging/src/stop.ts
- packages/office-addin-dev-certs/src/commands.ts
- packages/office-addin-dev-certs/src/install.ts
- packages/office-addin-dev-certs/src/uninstall.ts
- packages/office-addin-dev-certs/src/verify.ts
- packages/office-addin-lint/src/commands.ts
- packages/office-addin-lint/src/lint.ts
- packages/office-addin-manifest/src/commands.ts
- packages/office-addin-manifest/src/manifestInfo.ts
- packages/office-addin-manifest/src/validate.ts
- packages/office-addin-sso/src/authRoute.ts
- packages/office-addin-sso/src/commands.ts
- packages/office-addin-sso/src/configure.ts
- packages/office-addin-sso/src/server.ts
- packages/office-addin-sso/src/ssoDataSettings.ts
- packages/office-addin-usage-data/src/usageData.ts
- packages/office-addin-usage-data/test/test.ts
Added the new telemetry syntax to the following packages, which are all that had previously telemetry implemented: 
- office-addin-debugging 
- office-addin-dev-certs 
- office-addin-lint 
- office-addin-manifest 
- office-addin-sso
> Added the new telemetry syntax to the following packages, which are all that had previously telemetry implemented: 

- packages/office-addin-sso/package-lock.json
- packages/office-addin-sso/package.json
Fixing vulnerability warning for pug (other changes in package-lock file were done automatically).
> Update version of pug

- packages/office-addin-lint/config/.eslintrc.json
- packages/office-addin-lint/package-lock.json
- packages/office-addin-lint/package.json
- packages/office-addin-lint/src/cli.ts
- packages/office-addin-lint/src/defaults.ts
- packages/office-addin-lint/src/lint.ts
> office-addin-lint: update eslint-config-prettier

- packages/office-addin-lint/src/defaults.ts
> Revert default lintFiles expansion syntax

- packages/office-addin-debugging/src/port.ts
- packages/office-addin-dev-certs/src/install.ts
- packages/office-addin-dev-certs/src/uninstall.ts
- packages/office-addin-dev-certs/src/verify.ts
- packages/office-addin-dev-certs/test/test.ts
- packages/office-addin-manifest/test/test.ts
- packages/office-addin-test-helpers/test/test.ts
- packages/office-addin-test-server/test/test.ts
Since the last PR https://github.com/OfficeDev/Office-Addin-Scripts/pull/156 is stale, i've created a new PR to make some progress on the linux support topic.
> Add linux support to office-addin-dev-certs

- packages/custom-functions-metadata-plugin/package-lock.json
- packages/custom-functions-metadata-plugin/package.json
- packages/custom-functions-metadata-plugin/src/customfunctionsplugin.ts
- packages/custom-functions-metadata-plugin/src/loader.ts
- packages/custom-functions-metadata-plugin/tsconfig.json
- packages/office-addin-dev-settings/src/registry.ts
~This PR is the seed for solving https://github.com/OfficeDev/Office-Addin-Scripts/issues/421. I mean seed because I couldn't test it. I wasn't able to setup the project on my machine (running npm ci fails), so I tried my best to guess some implementation details. I hope you're able to test it and fix whatever is still missing.~
This PR fixes #421.
I followed [this recommendation](https://github.com/webpack/webpack/issues/10081) and moved the code injection to a custom loader. I also updated the hooks and taps to not rely on deprecated APIs.
> Use loader to inject function associations

- package-lock.json
- packages/eslint-plugin-excel-custom-functions/package-lock.json
- packages/office-addin-test-helpers/package-lock.json
- packages/office-addin-usage-data/package-lock.json
Ran npm audit fix on each of the packages and the root to fix existing vulnerabilities.
> fix package vulnerabilities

- packages/eslint-config-office-addins/package-lock.json
- packages/eslint-config-office-addins/src/main.ts
Has an invalid eslint configuration referent to plugins.  Updating to match the other references that have been verified.
> Correct reference to plugins in eslint-config-office-addins

- packages/custom-functions-metadata-plugin/package-lock.json
- packages/custom-functions-metadata/package-lock.json
- packages/eslint-plugin-excel-custom-functions/package-lock.json
- packages/office-addin-debugging/package-lock.json
- packages/office-addin-dev-certs/package-lock.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-lint/package-lock.json
- packages/office-addin-manifest/package-lock.json
- packages/office-addin-node-debugger/package-lock.json
- packages/office-addin-sso/package-lock.json
- packages/office-addin-test-server/package-lock.json
- packages/office-addin-usage-data/package-lock.json
The updates the package lock file to take care of known vulnerabilities as well and updates package-lock.json files in general to try to avoid future vulnerabilities.
> Update package references in packages

- packages/eslint-plugin-office-addins/package-lock.json
- packages/eslint-plugin-office-addins/package.json
- packages/eslint-plugin-office-addins/src/main.ts
- packages/eslint-plugin-office-addins/src/rules/index.ts
- packages/eslint-plugin-office-addins/src/rules/no-context-sync-in-loop.ts
- packages/eslint-plugin-office-addins/src/rules/no-office-initialize.ts
- packages/eslint-plugin-office-addins/src/rules/test-for-null-using-isNullObject.ts
- packages/eslint-plugin-office-addins/test/rules/test-for-null-using-isNullObject.test.ts
Note that the current implementation does not distinguish weather or not a variable is set to the "*OrNullObject" result before it is used in a test . . . only that if a variable is set to the "*OrNullObject" at some point then there test of that object are using the isNullObject property.
It also contains a fix method.
> New is null object rule

- packages/office-addin-manifest/package-lock.json
- packages/office-addin-manifest/package.json
- packages/office-addin-manifest/src/manifestInfo.ts
- packages/office-addin-manifest/test/test.ts
> Update uuid package to 8.3.2

- package-lock.json
- package.json
- packages/eslint-config-office-addins/package-lock.json
- packages/eslint-config-office-addins/package.json
- packages/eslint-plugin-office-addins/package-lock.json
- packages/eslint-plugin-office-addins/package.json
- packages/office-addin-sso/package-lock.json
- packages/office-addin-sso/package.json
Clears up all but 2 vulnerabilities resulting from lerna dependancy
> Update lerna to v4

- packages/eslint-plugin-office-addins/test/rules/load-object-before-read.test.ts
Making all the tests available again
> Removing comments on the test

- packages/custom-functions-metadata-plugin/package-lock.json
- packages/custom-functions-metadata/package-lock.json
- packages/eslint-config-office-addins/package-lock.json
- packages/eslint-plugin-excel-custom-functions/package-lock.json
- packages/office-addin-cli/package-lock.json
- packages/office-addin-debugging/package-lock.json
- packages/office-addin-dev-certs/package-lock.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-lint/package-lock.json
- packages/office-addin-manifest/package-lock.json
- packages/office-addin-node-debugger/package-lock.json
- packages/office-addin-sso/package-lock.json
- packages/office-addin-test-helpers/package-lock.json
- packages/office-addin-test-server/package-lock.json
- packages/office-addin-usage-data/package-lock.json
Somewhere in the updating of dependencies many lock files got out of sync with their package files such the the clean install command didn't work.  When through the process of doing an install command followed by the clean install command followed by the build and test commands.
> Update lock files to match updated package files

- packages/eslint-config-office-addins/package-lock.json
- packages/eslint-plugin-excel-custom-functions/package-lock.json
- packages/eslint-plugin-office-addins/package-lock.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-dev-settings/package.json
- packages/office-addin-lint/package-lock.json
- packages/office-addin-node-debugger/package-lock.json
- packages/office-addin-sso/package-lock.json
- packages/office-addin-test-server/package-lock.json
- packages/office-addin-usage-data/package-lock.json
Ran `npm install` then `npm audit fix` on each package.
> Run audit fix on all packages

- packages/eslint-plugin-office-addins/src/rules/call-sync-after-load.ts
- packages/eslint-plugin-office-addins/src/rules/load-object-before-read.ts
- packages/eslint-plugin-office-addins/src/rules/no-navigational-load.ts
- packages/eslint-plugin-office-addins/test/rules/call-sync-after-load.test.ts
- packages/eslint-plugin-office-addins/test/rules/load-object-before-read.test.ts
- packages/eslint-plugin-office-addins/test/rules/no-empty-load.test.ts
- packages/eslint-plugin-office-addins/test/rules/no-navigational-load.test.ts
Making eslint support the syntax of using load("*")
> Adding support to load(*) to eslint rules

- packages/office-addin-mock/README.md
Some very small text fix to the readme
> Small Fix in readme sintax

- packages/office-addin-mock/src/officeMockObject.ts
- packages/office-addin-mock/test/officeMockObject.test.ts
Fixes https://github.com/OfficeDev/Office-Addin-Scripts/issues/561.
Now supporting loading of arrays inside objects. Also added more tests for supporting arrays
> Array inside object

- packages/office-addin-mock/src/officeMockObject.ts
- packages/office-addin-mock/test/officeMockObject.test.ts
Merging `addMockFunction` and `setMock` into `setProperty` for more name clarity.
> Renaming functions

- package-lock.json
- packages/custom-functions-metadata-plugin/package-lock.json
- packages/custom-functions-metadata/package-lock.json
- packages/eslint-config-office-addins/package-lock.json
- packages/eslint-plugin-excel-custom-functions/package-lock.json
- packages/eslint-plugin-office-addins/package-lock.json
- packages/office-addin-cli/package-lock.json
- packages/office-addin-debugging/package-lock.json
- packages/office-addin-dev-certs/package-lock.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-lint/package-lock.json
- packages/office-addin-manifest/package-lock.json
- packages/office-addin-mock/package-lock.json
- packages/office-addin-node-debugger/package-lock.json
- packages/office-addin-prettier-config/package-lock.json
- packages/office-addin-sso/package-lock.json
- packages/office-addin-test-helpers/package-lock.json
- packages/office-addin-test-server/package-lock.json
- packages/office-addin-usage-data/package-lock.json
Ran 'npm run install-packages' and 'npm run audit:fix'
> Updating lock files and fixing vulnerabilities

- packages/office-addin-mock/README.md
Removing deprecated functions from readme in mock package.
> Removing deprecated function from readme

- packages/office-addin-sso/package-lock.json
- packages/office-addin-sso/package.json
Replacing copy command to another that doesn't have vulnerabilities.
> Fix sso vulnerability

- packages/office-addin-manifest/package.json
> move fs-extra to dependencies

- packages/custom-functions-metadata-plugin/package-lock.json
- packages/custom-functions-metadata/package-lock.json
- packages/eslint-config-office-addins/package-lock.json
- packages/eslint-plugin-excel-custom-functions/package-lock.json
- packages/eslint-plugin-office-addins/package-lock.json
- packages/office-addin-cli/package-lock.json
- packages/office-addin-debugging/package-lock.json
- packages/office-addin-dev-certs/package-lock.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-lint/package-lock.json
- packages/office-addin-manifest/package-lock.json
- packages/office-addin-mock/package-lock.json
- packages/office-addin-node-debugger/package-lock.json
- packages/office-addin-prettier-config/package-lock.json
- packages/office-addin-sso/package-lock.json
- packages/office-addin-test-helpers/package-lock.json
- packages/office-addin-test-server/package-lock.json
- packages/office-addin-usage-data/package-lock.json
> Update script package version references

- packages/office-addin-manifest/package-lock.json
- packages/office-addin-manifest/package.json
- packages/office-addin-manifest/src/manifestHandler/manifestHandler.ts
- packages/office-addin-manifest/src/manifestHandler/manifestHandlerJson.ts
- packages/office-addin-manifest/src/manifestHandler/manifestHandlerXml.ts
- packages/office-addin-manifest/src/manifestOperations.ts
- packages/office-addin-manifest/test/manifests/manifest.json
- packages/office-addin-manifest/test/test.ts
Added manifest JSON manipulation code.
> Added JSON manifest manipulation

- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-dev-settings/package.json
- packages/office-addin-dev-settings/src/commands.ts
- packages/office-addin-dev-settings/src/dev-settings-mac.ts
- packages/office-addin-dev-settings/src/dev-settings-windows.ts
- packages/office-addin-dev-settings/src/dev-settings.ts
- packages/office-addin-dev-settings/src/publish.ts
- packages/office-addin-dev-settings/test/files/manifests/manifest.json
- packages/office-addin-dev-settings/test/unit-tests/test.ts
- packages/office-addin-dev-settings/tsconfig.json
- packages/office-addin-manifest/.vscode/launch.json
- packages/office-addin-manifest/README.md
- packages/office-addin-manifest/src/cli.ts
- packages/office-addin-manifest/src/commands.ts
- packages/office-addin-manifest/src/export.ts
- packages/office-addin-manifest/src/main.ts
- packages/office-addin-manifest/test/manifests/manifest.json
- packages/office-addin-manifest/test/test.ts
This should allow for sideloading the json version of the manifest.
> Update registering the add-in to publish a packaged json manifest.

- packages/office-addin-debugging/package-lock.json
- packages/office-addin-debugging/package.json
- packages/office-addin-sso/package-lock.json
- packages/office-addin-sso/package.json
- packages/office-addin-test-helpers/package-lock.json
- packages/office-addin-test-helpers/package.json
- packages/office-addin-test-server/package-lock.json
- packages/office-addin-test-server/package.json
Fix component governance reported vulnerability
> Update express package version

- packages/office-addin-project/README.md
- packages/office-addin-project/package-lock.json
- packages/office-addin-project/package.json
- packages/office-addin-project/src/cli.ts
- packages/office-addin-project/src/commands.ts
- packages/office-addin-project/src/convert.ts
Zipping and backing up project before running the convert command
> Creating backup folder for project command

- packages/office-addin-manifest/package-lock.json
- packages/office-addin-manifest/package.json
- packages/office-addin-manifest/src/manifestHandler/manifestHandlerJson.ts
- packages/office-addin-manifest/src/officeApp.ts
- packages/office-addin-manifest/test/manifests/manifest.json
- packages/office-addin-manifest/test/test.ts
Updated manifest manipulation code to test and get all fields.
> Manipulating json

- packages/custom-functions-metadata-plugin/package-lock.json
- packages/custom-functions-metadata/package-lock.json
- packages/custom-functions-metadata/package.json
- packages/office-addin-dev-settings/package-lock.json
Ran 'npm audit fix' and 'npm audit fix --force' for custom-functions-metadata
Note that custom-functions-metadata-plugin needs the updated metadata package in order to resolve it's last vulnerability/
> Fixing reported Vulnerabilities

- packages/office-addin-dev-settings/src/sideload.ts
Fixes a but with using the package in a project where it's imported.
> Update path to call DevXTool.exe

- packages/custom-functions-metadata-plugin/package-lock.json
- packages/custom-functions-metadata/package-lock.json
- packages/eslint-config-office-addins/package-lock.json
- packages/eslint-plugin-excel-custom-functions/package-lock.json
- packages/eslint-plugin-office-addins/package-lock.json
- packages/office-addin-cli/package-lock.json
- packages/office-addin-debugging/package-lock.json
- packages/office-addin-dev-certs/package-lock.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-lint/package-lock.json
- packages/office-addin-manifest/package-lock.json
- packages/office-addin-manifest/package.json
- packages/office-addin-manifest/test/test.ts
- packages/office-addin-mock/package-lock.json
- packages/office-addin-node-debugger/package-lock.json
- packages/office-addin-prettier-config/package-lock.json
- packages/office-addin-project/package-lock.json
- packages/office-addin-sso/package-lock.json
- packages/office-addin-test-helpers/package-lock.json
- packages/office-addin-test-server/package-lock.json
- packages/office-addin-usage-data/package-lock.json
---
Add 'tslib' dependency to work around the lack of it in the teams-manifest library
No.
No.
Just ran …
> [minor] Fix tslib dependency

- .azure-devops/steps/npm-install.yaml
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-manifest/package-lock.json
- packages/office-addin-manifest/package.json
---
There was a missing dependency in the teams-mainfest package.  The updated the package to remove the need for tslib so we can also remove the workaround we have in place.
No.
No.
> Include 'Rick-Kirkham' in the …
> [patch] Remove tslib package dependency

- package-lock.json
- package.json
- packages/office-addin-debugging/package-lock.json
- packages/office-addin-dev-settings/package-lock.json
---
Updated some package and the lock files to fix some vulnerabilities.
No
No
Ran lerna commands and …
> [patch] Fix vulnerabilities

- packages/office-addin-sso/.gitignore
---
Remove the .gitignore file from office-addin-sso which is preventing the build output from being published.
No.
No. …
> [patch] Remove sso .gitignore file

- packages/office-addin-project/src/convert.ts
Just adding a small message to warn that JSON manifest is not supported
> [patch] Adding message to say JSON is not yet supported

- packages/office-addin-manifest/package-lock.json
- packages/office-addin-manifest/package.json
- packages/office-addin-manifest/src/manifestHandler/manifestHandlerJson.ts
- packages/office-addin-manifest/test/manifests/devPreviewManifest.json
- packages/office-addin-manifest/test/manifests/manifest.json
- packages/office-addin-manifest/test/test.ts
---
json manifest parsing was setup for the dev preview schema.  Updated to handle both devpreview and current schemas and updated tests to test both cases.
No.
No.
> Make sure …
> [patch] Update manifest parsing

- packages/office-addin-dev-settings/src/publish.ts
---
Currently Outlook doesn't update when sideloading json manifest based add-in more than hour.  We can work around this by deleting a cache file that is used to determine the need to update, thus forcing an update the next time Outlook is run.
No.
No.
If you answered yes to …
> [patch] Add force update for json manifest app cache

- usage-data.md
---
Adding a notice about the collection of deviceID.
> Make sure the README file is …
> [Patch] Adding GUID notice

- package-lock.json
- package.json
- packages/office-addin-sso/package-lock.json
---
Added an override to root package.json and ran audit fix on office-addin-sso.
No.
No.
Ran build and …
> Fix vulnerabilities

- packages/office-addin-project/package.json
- packages/office-addin-project/src/convert.ts
---
Made the conversion check for any errors before making changes to the project (such as in the `packge.json`.
No
No …
> [Patch] Making conversion not leave project on bad state

- packages/office-addin-debugging/package-lock.json
- packages/office-addin-debugging/package.json
- packages/office-addin-dev-certs/package-lock.json
- packages/office-addin-dev-certs/package.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-dev-settings/package.json
- packages/office-addin-node-debugger/package-lock.json
- packages/office-addin-node-debugger/package.json
---
Customer reported that child_process package was removed because of security concerns and that the node module should be used instead.  Removing package.json reference to child_process
No.
No.
> Include …
> Remove child_process package from package.json files

- packages/office-addin-dev-settings/src/sideload.ts
---
Remove an unneeded conditional for looking up the host name based on the json scope.
No
No
Made …
> [patch] Remove json switch for host name

- packages/custom-functions-metadata-plugin/package-lock.json
- packages/custom-functions-metadata-plugin/package.json
---
Update loader-utils to fixed version
No.
No.
Describe manual testing done.
> [patch] Update loader-utils package version

- packages/office-addin-debugging/package-lock.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-project/package-lock.json
- packages/office-addin-project/package.json
---
npm audit fix
No.
No.
Describe manual testing done.
> [patch] Fix xmldom vulnerability

- packages/custom-functions-metadata/package-lock.json
- packages/eslint-config-office-addins/package-lock.json
- packages/eslint-plugin-office-addins/package-lock.json
- packages/office-addin-cli/package-lock.json
- packages/office-addin-lint/package-lock.json
- packages/office-addin-manifest/package-lock.json
- packages/office-addin-sso/package-lock.json
- packages/office-addin-test-helpers/package-lock.json
- packages/office-addin-test-server/package-lock.json
---
Ran npm audit fix on projects with minimatch vulnerability
No.
No.
Ran automated tests
> [patch] Fixing minimatch vulnerability

- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-dev-settings/package.json
- packages/office-addin-dev-settings/src/publish.ts
---
The publish version of the teamsfx-cli package we depend on now includes the functionality we require.  Switching installed package from the alpha version to a released version.
No.
No.
> Include 'Rick-Kirkham' …
> [patch] Switch from alpha teamsfx-cli to released

- packages/office-addin-dev-certs/package-lock.json
- packages/office-addin-dev-certs/src/cli.ts
- packages/office-addin-dev-certs/src/commands.ts
- packages/office-addin-dev-certs/src/verify.ts
---
When domain argument is empty there was an error even though a default was used later.  This change allows for undefined being allowed and the default value to be used.
No.
No.
> Include 'Rick-Kirkham' in the …
> [patch] Fix cert domain defaults

- packages/office-addin-dev-certs/src/commands.ts
---
Fix spelling mistake
No.
No.
ran tests.
> [patch] Correct spelling of "sting" to "string"

- packages/office-addin-dev-settings/src/sideload.ts
---
Fix spelling mistake from last checking
No.
No.
Verified spelling.
> Fix spelling mistage in error message

- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-dev-settings/package.json
- packages/office-addin-manifest/package-lock.json
- packages/office-addin-manifest/test/manifests/teamsManifest.json
---
Updating dependencies to fix vulnerabilities
No.
No.
Ran automated tests
> [minor] Fix vulnerabilities

- packages/office-addin-debugging/package-lock.json
---
After fixing vulnerability in office-addin-dev-settings I needed to update the lock file in office-addin-debugging to clear the vulnerability
No.
No.
> Make sure the README …
> Ran npm install on office-addin-debugging

- .github/pull_request_template.md
- packages/office-addin-manifest/README.md
- packages/office-addin-mock/README.md
- packages/office-addin-project/README.md
- Updates the doc links from docs.microsoft.com to learn.microsoft.com in affected README files and the PR template.
- Suggests minor formatting and typo corrections.
No.
1. **Do these changes impact *documentation*?** (e.g., a tutorial on https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins)
No.
N/A
> [minor] Update doc links in README files and PR template

- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-dev-settings/package.json
- packages/office-addin-dev-settings/src/sideload.ts
---
Update the teamsfx-cli dependency.  Remove check for environment variables that teamsfx-cli used to depend on during office-addin-dev-settings sideload command.
No.
No.
> Make …
> [patch] Update teamsfx-cli and remove env check on sidelaod

- packages/office-addin-sso/src/configure.ts
---
Add a check for servicePrinicipalObjectlId when trying to setup the reply urls.  This was causing a configuration failure reported by customers.
No.
No.
> Make sure the README …
> [patch] Test for servicePrinicipalObjectlId in sso configure

- packages/eslint-plugin-excel-custom-functions/package-lock.json
- packages/eslint-plugin-excel-custom-functions/package.json
- packages/office-addin-debugging/package-lock.json
- packages/office-addin-dev-settings/package-lock.json
---
Updating some package dependencies to avoid vulnerabilities.
No.
No.
built and ran automated tests.
> [patch] Ran 'audit fix' in a couple projects and removed unneeded packages.

- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-dev-settings/package.json
---
Update version of teamsfx-cli used to fix vulnerability. 
No.
No.
Ran automated tests
> [patch] Update teamsfx-cli version

- packages/office-addin-project/package-lock.json
- packages/office-addin-project/package.json
---
Update the office-addin-manifest-converter package version used in office-addin-project package
No.
No. …
> [patch] Update manifest converter package version

- packages/office-addin-manifest/package-lock.json
- packages/office-addin-manifest/package.json
- packages/office-addin-manifest/src/export.ts
- packages/office-addin-manifest/src/manifestHandler/manifestHandlerJson.ts
- packages/office-addin-manifest/src/validate.ts
---
Updating the @microsoft/teams-manifest package version and related object references in code.
No.
No. …
> [patch] Update json manifest package

- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-dev-settings/package.json
> Making @microsoft/teamsfx-cli a peer dependency

- package-lock.json
- packages/custom-functions-metadata-plugin/package-lock.json
- packages/custom-functions-metadata/package-lock.json
- packages/eslint-config-office-addins/package-lock.json
- packages/eslint-plugin-excel-custom-functions/package-lock.json
- packages/eslint-plugin-office-addins/package-lock.json
- packages/office-addin-cli/package-lock.json
- packages/office-addin-debugging/package-lock.json
- packages/office-addin-dev-certs/package-lock.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-lint/package-lock.json
- packages/office-addin-manifest/package-lock.json
- packages/office-addin-mock/package-lock.json
- packages/office-addin-node-debugger/package-lock.json
- packages/office-addin-project/package-lock.json
- packages/office-addin-sso/package-lock.json
- packages/office-addin-test-helpers/package-lock.json
- packages/office-addin-test-server/package-lock.json
- packages/office-addin-usage-data/package-lock.json
Ran npm audit fix on various packages to update semver to fix vulnerabilities in the package.
> [minor] Fix Semver Errors

- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-dev-settings/package.json
- packages/office-addin-dev-settings/src/publish.ts
---
Updating the version of teamsfx-cli to an alpha version that takes care of their vulnerability.  Note that teams fx won't ship the fix until next month, but the vulnerability is a critical one, so we are taking this change now and that will have to make an update to the shipped version later.
No.
2. **Do these changes impact *documentation*?** (e.g., a tutorial on …
> [patch] Fix teamsfx-cli vulnerability

- packages/eslint-plugin-excel-custom-functions/package-lock.json
- packages/eslint-plugin-office-addins/package-lock.json
- packages/office-addin-debugging/package-lock.json
---
Updating lock files
No.
No.
Ran automated tests.
> npm audit fix on 3 packages

- package-lock.json
- package.json
---
Indicate support for npm v10
No.
No.
Ran npm install and automated tests with npm v10 installed.
> [patch] Mark support for npm v10

- package-lock.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-dev-settings/package.json
- packages/office-addin-dev-settings/src/appcontainer.ts
- packages/office-addin-dev-settings/src/dev-settings-mac.ts
- packages/office-addin-dev-settings/src/dev-settings-windows.ts
- packages/office-addin-dev-settings/src/publish.ts
- packages/office-addin-dev-settings/src/sideload.ts
- packages/office-addin-dev-settings/test/unit-tests/test.ts
- packages/office-addin-manifest/package-lock.json
- packages/office-addin-sso/package-lock.json
---
Update the teamsfx-cli to current teamsapp-cli to fix outstanding vulnerability and change to new api arguments.  Also fixed other package vulnerabilities
No.
No.
> Make sure …
> [patch] Update teamsfx-cli to teamsapp-cli

- packages/office-addin-project/package-lock.json
- packages/office-addin-project/package.json
---
Update office-addin-manifest-converter package dependency version
No.
No.
Ran automated test and …
> [patch] Update package dependency version

- package-lock.json
- packages/custom-functions-metadata-plugin/package-lock.json
- packages/eslint-config-office-addins/package-lock.json
- packages/eslint-plugin-excel-custom-functions/package-lock.json
- packages/office-addin-cli/package-lock.json
- packages/office-addin-debugging/package-lock.json
- packages/office-addin-dev-certs/package-lock.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-mock/package-lock.json
- packages/office-addin-node-debugger/package-lock.json
- packages/office-addin-sso/package-lock.json
- packages/office-addin-test-helpers/package-lock.json
- packages/office-addin-test-server/package-lock.json
Lockfile update prior to publish . . . only ran 'npm run install-packages' from repo root.
> Update package-lock files

- packages/eslint-plugin-office-addins/src/main.ts
- packages/eslint-plugin-office-addins/test/rules/call-sync-after-load.test.ts
- packages/eslint-plugin-office-addins/test/rules/call-sync-before-read.test.ts
- packages/eslint-plugin-office-addins/test/rules/load-object-before-read.test.ts
- packages/eslint-plugin-office-addins/test/rules/no-context-sync-in-loop.test.ts
- packages/eslint-plugin-office-addins/test/rules/no-empty-load.test.ts
- packages/eslint-plugin-office-addins/test/rules/no-navigational-load.test.ts
- packages/eslint-plugin-office-addins/test/rules/no-office-initialize.test.ts
- packages/eslint-plugin-office-addins/test/rules/test-for-null-using-isNullObject.test.ts
- packages/eslint-plugin-office-addins/tsconfig.json
---
The linter rules got broken in the last big change.  Needed to remove the test building from the tsconfig and also remove the dependency on tsconfig.json in the lint configuration.   Also fixed prettier problems in the rules files.
No.,
No.
If you answered yes to any of these …
> [patch] Fix linter rules

- package-lock.json
- packages/office-addin-sso/package-lock.json
Upgrade packages to fix security vulnerabilities
> Upgrade packages to fix security vulnerabilities

- packages/office-addin-dev-settings/package-lock.json
---
Fixing dependencies by running npm audit fix …
> [minor] Fixing dependencies

- packages/office-addin-debugging/package-lock.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-manifest/package-lock.json
- packages/office-addin-mock/package-lock.json
- packages/office-addin-project/package-lock.json
- packages/office-addin-sso/package-lock.json
> Update axios dependencies

- packages/custom-functions-metadata/Specification.md
- packages/custom-functions-metadata/package-lock.json
- packages/custom-functions-metadata/src/parseTree.ts
- packages/custom-functions-metadata/test/cases/capturesCallingObject/expected.json
- packages/custom-functions-metadata/test/cases/capturesCallingObject/functions.js
- packages/custom-functions-metadata/test/cases/capturesCallingObject/functions.ts
- packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-capturesCallingObject/expected.js.errors.txt
- packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-capturesCallingObject/expected.ts.errors.txt
- packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-capturesCallingObject/functions.js
- packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-capturesCallingObject/functions.ts
---
Handle @capturesCallingObject metadata tag for Excel javascript custom functions
No
Yes, but will be handled separately to indicate what the flag means
> Make sure the README …
> [minor] Add @capturesCallingObject tag handling

- package-lock.json
- packages/custom-functions-metadata-plugin/package-lock.json
- packages/custom-functions-metadata-plugin/package.json
- packages/custom-functions-metadata/package-lock.json
- packages/eslint-config-office-addins/package-lock.json
- packages/eslint-plugin-excel-custom-functions/package-lock.json
- packages/eslint-plugin-excel-custom-functions/package.json
- packages/eslint-plugin-excel-custom-functions/tests/tsconfig.test.json
- packages/eslint-plugin-office-addins/package-lock.json
- packages/office-addin-cli/package-lock.json
- packages/office-addin-cli/package.json
- packages/office-addin-debugging/package-lock.json
- packages/office-addin-dev-certs/package-lock.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-lint/package-lock.json
- packages/office-addin-lint/package.json
- packages/office-addin-manifest/package-lock.json
- packages/office-addin-mock/package-lock.json
- packages/office-addin-node-debugger/package-lock.json
- packages/office-addin-project/package-lock.json
- packages/office-addin-sso/package-lock.json
- packages/office-addin-test-helpers/package-lock.json
- packages/office-addin-test-server/package-lock.json
- packages/office-addin-usage-data/package-lock.json
- packages/office-addin-usage-data/package.json
Updated some dependent package and ran 'npm audit fix' to correct for reported vulnerabilities.
No.
No.
Ran automated test and check the audit report for each package.
> [patch] Updated some dependencies and ran "npm audit fix" for other cases.

- packages/office-addin-debugging/package-lock.json
- packages/office-addin-debugging/package.json
- packages/office-addin-dev-certs/package-lock.json
- packages/office-addin-dev-certs/package.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-dev-settings/package.json
- packages/office-addin-sso/package-lock.json
- packages/office-addin-sso/package.json
- packages/office-addin-test-server/package-lock.json
- packages/office-addin-test-server/package.json
- packages/office-addin-usage-data/package-lock.json
- packages/office-addin-usage-data/package.json
---
Updated some packages used to fix vulnerabilities
No.
No.
Ran automated tests
> [patch] Updated dependencies used in various packages

- .azure-devops/full-pipeline.yml
- packages/office-addin-project/package-lock.json
- packages/office-addin-project/package.json
update office-addin-manifest-converter version used in office-addin-project package.
No.
No.
Ran automated tests.  Will be verified more by toolkit team.
> [patch] Update office-addin-manifest-converter to the latest version

- packages/office-addin-sso/package.json
- packages/office-addin-test-helpers/package.json
- packages/office-addin-test-server/package.json
Lerna made a mistake and didn't bump these package version to publish.  Manually correcting that.
No.
No.
Can't test this change.
> [patch] Bump versions of packages to publish

- .azure-devops/full-pipeline.yml
- package-lock.json
- packages/custom-functions-metadata-plugin/package-lock.json
- packages/custom-functions-metadata/package-lock.json
- packages/eslint-config-office-addins/package-lock.json
- packages/eslint-plugin-excel-custom-functions/package-lock.json
- packages/eslint-plugin-office-addins/package-lock.json
- packages/office-addin-cli/package-lock.json
- packages/office-addin-debugging/package-lock.json
- packages/office-addin-dev-certs/package-lock.json
- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-lint/package-lock.json
- packages/office-addin-manifest/package-lock.json
- packages/office-addin-mock/package-lock.json
- packages/office-addin-node-debugger/package-lock.json
- packages/office-addin-project/package-lock.json
- packages/office-addin-sso/package-lock.json
- packages/office-addin-test-helpers/package-lock.json
- packages/office-addin-test-server/package-lock.json
- packages/office-addin-usage-data/package-lock.json
> Updating cross-spawn to 7.0.6

- packages/office-addin-dev-settings/package-lock.json
- packages/office-addin-dev-settings/package.json
- packages/office-addin-dev-settings/src/commands.ts
- packages/office-addin-dev-settings/src/dev-settings-windows.ts
- packages/office-addin-dev-settings/src/dev-settings.ts
- packages/office-addin-dev-settings/src/publish.ts
- packages/office-addin-dev-settings/test/unit-tests/test.ts
Updated the teamsapp-cli package and the new arguments that it requires.  Also fixed a bug where xml was still being sideloaded to the service for WXP when those aren't supported yet.
No.  this is all internal
No.
Ran (and updated) automated tests.  Also tried updated packages in test project for both Outlook and Excel.
> [patch] Update unrigister command for json manifests

- packages/custom-functions-metadata/package-lock.json
- packages/custom-functions-metadata/src/parseTree.ts
This change makes minor updates to parseTree.ts. The changes are dedicated for custom functions of ScriptLab. No impact to the custom-functions-metadata package.
No
No
Validated with `npm run test`.
> [patch] Update parseTree.ts for custom function metadata to align with ScriptLab

- packages/office-addin-debugging/package-lock.json
- packages/office-addin-dev-settings/package-lock.json
> Update Vulnerable Packages

- package-lock.json
- packages/office-addin-manifest/package.json
Update the dependency on @microsoft/app-manifest to be the shipped version of the package
No.
No
Ran automated test and manually tried with a test project.
> [patch] use published manifest package

- packages/custom-functions-metadata/src/parseTree.ts
- packages/custom-functions-metadata/test/cases/error-supportsync-conflict-option/expected.js.errors.txt
- packages/custom-functions-metadata/test/cases/error-supportsync-conflict-option/expected.ts.errors.txt
- packages/custom-functions-metadata/test/cases/error-supportsync-conflict-option/functions.js
- packages/custom-functions-metadata/test/cases/error-supportsync-conflict-option/functions.ts
- packages/custom-functions-metadata/test/cases/error-supportsync-missing-invocation-parameter/expected.js.errors.txt
- packages/custom-functions-metadata/test/cases/error-supportsync-missing-invocation-parameter/expected.ts.errors.txt
- packages/custom-functions-metadata/test/cases/error-supportsync-missing-invocation-parameter/functions.js
- packages/custom-functions-metadata/test/cases/error-supportsync-missing-invocation-parameter/functions.ts
- packages/custom-functions-metadata/test/cases/supportSync/expected.json
- packages/custom-functions-metadata/test/cases/supportSync/functions.js
- packages/custom-functions-metadata/test/cases/supportSync/functions.ts
> Add @supportSync tag
