packages/office-addin-test-server/src/testServer.ts

- Per suggestion of AKrantz: "There is no try/catch around the await to call reject on the Promise which is returned. Await on a rejected promise throws from that point. I highly suggest not mixing async/await code with callbacks that resolve/reject a Promise in the same function. Its too easy to miss things"
- Validated tests pass
- Also linked changes to Office-Addin-Taskpane and validated UI tests pass

Move test server listener code to separate function

---

packages/custom-functions-metadata-plugin/package-lock.json
packages/custom-functions-metadata/package-lock.json
packages/office-addin-cli/package-lock.json
packages/office-addin-debugging/package-lock.json
packages/office-addin-dev-certs/package-lock.json
packages/office-addin-dev-settings/package-lock.json
packages/office-addin-manifest/package-lock.json
packages/office-addin-node-debugger/package-lock.json
packages/office-addin-test-helpers/package-lock.json
packages/office-addin-test-server/package-lock.json
packages/office-addin-test-server/package.json

Verison 1.0.0 had already been published -- not sure why -- so need to bump version to 1.0.1.
This caused all of the package-lock.json files to be updated.

update test server version

---

packages/custom-functions-metadata/src/generate.ts
packages/custom-functions-metadata/test/cases/return-type-explicit/expected.json
packages/custom-functions-metadata/test/cases/return-type-explicit/functions.js
packages/custom-functions-metadata/test/cases/return-type-explicit/functions.ts
packages/custom-functions-metadata/test/cases/return-type-implicit/expected.json
packages/custom-functions-metadata/test/cases/return-type-implicit/functions.js
packages/custom-functions-metadata/test/cases/return-type-implicit/functions.ts

Fixes https://github.com/OfficeDev/Office-Addin-Scripts/issues/172
* Add test cases for Promise return types.
* Fix code to handle Promise return types in the @returns JSDoc tag.

custom-functions-metadata: ensure Promise return type works for TypeScript and JavaScript

---

packages/office-addin-prettier-config/package-lock.json
packages/office-addin-prettier-config/package.json
packages/office-addin-prettier-config/prettier.config.js

This creates a shared prettier config for Office-Addins. Packages that want to use it can add the following to package.json : "prettier": "office-addin-prettier-config"

shared prettier config

---

packages/office-addin-debugging/src/start.ts
packages/office-addin-dev-settings/src/sideload.ts

Need better logic for the case where the is an app specified and the manifest contains multiple hosts.

office-addin-dev-settings: fix sideload command

---

packages/office-addin-dev-settings/src/dev-settings.ts

On Windows, if the register command is called with a relative path or just a file name,
the full path should be written into the registry.

office-addin-dev-settings: register command should write full path

---

packages/office-addin-dev-certs/src/install.ts
packages/office-addin-dev-certs/test/test.ts

The ampersand should not be in the command. It causes it to execute as two separate commands
and opens the script file rather than executing it.

office-addin-dev-certs: fix install

---

packages/office-addin-dev-settings/test/integration-tests/test.ts

Fix unit tests so they don't hang on enabling EdgeWV loopback
- Tests were hanging in CI loop due to prompt surfacing for enabling Edge Webview loopback
- Set command.yes to true to bypass prompt

Fix office addin dev settings tests

---

packages/office-addin-debugging/README.md
packages/office-addin-debugging/src/cli.ts
packages/office-addin-debugging/src/commands.ts
packages/office-addin-debugging/src/start.ts

- Replace app-type with platform param
- If manifestPath is an empty string, determine the manifest path via the platform and new --prod option. This allows for the creation the correct manifest for SDX's where the manifest is copied to the dist folder as part of build
- Remove the --unload option for stop, which as far as I can tell is no longer used
- Tested this to ensure backwards compat and to ensure it can construct the manifest path correctly when the manifest is in the dist folder

Implement sideloading for bundled manifest

---

package.json

Add a script which can update the latest dist-tag for the packages to the value of the next dist-tag.
To publish updated packages, the process becomes:
1. Use `npm run publish:next` to publish the packages to NPM using the "next" dist-tag.
2. Validate the packages published to the next dist-tag.
3. Use `npm run update-latest-dist-tags` to update the "latest" dist-tag to the value of the "next" dist-tag.

add script to update latest dist-tags

---

packages/custom-functions-metadata/src/testfunctions.ts
packages/custom-functions-metadata/test/src/test.ts
packages/custom-functions-metadata/test/typescript/testfunctions.ts
packages/office-addin-manifest/src/commands.ts
packages/office-addin-manifest/test/manifests/ScriptLab-v1.3.2.0.manifest.xml

The `dev.office.com` site was deprecated a while back; Office Add-ins docs now reside on the `docs.microsoft.com` site. This PR updates URLs accordingly.

Update docs URLs

---

packages/custom-functions-metadata-plugin/package-lock.json
packages/custom-functions-metadata/package-lock.json
packages/office-addin-debugging/package-lock.json
packages/office-addin-debugging/package.json
packages/office-addin-dev-certs/package-lock.json
packages/office-addin-dev-certs/package.json
packages/office-addin-dev-settings/package-lock.json
packages/office-addin-lint/package-lock.json
packages/office-addin-lint/package.json
packages/office-addin-manifest/package-lock.json
packages/office-addin-manifest/package.json
packages/office-addin-manifest/test/test.ts
packages/office-addin-sso/package-lock.json
packages/office-addin-sso/package.json
packages/office-addin-usage-data/package-lock.json

Two goals with this PR:
- Update the version of usage-data that consuming packages use
- Commenting out a flaky test in office-addin-manifest
- The test covers how the package handles invalid manifest file paths
- Despite failing in our build pipeline, this test passes in another Mac machine
- A new bug work item to fix this will be added

Update versions of packages consuming usage-data, removing manifest test that's flaky on Mac

---

packages/office-addin-sso/src/commands.ts
packages/office-addin-sso/src/configure.ts

- setSharePointTenantReplyUrls was failing because it was using the tenant displayName, which can have spaces in it, rather than the actual tenant name
- the fix is to extract the tenant name from the application publisherDomain property and pass it to setSharePointTenantReplyUrls

Fixes Issue 518

---

packages/office-addin-usage-data/src/defaults.ts
packages/office-addin-usage-data/src/usageData.ts

- The fix is to ensure office-addin-scripts packages don't write out the office-addin-usage-data file before Yo Office does
- Created an array of office-addin-scripts packages currently consuming office-addin-usage-data package and check if the project name is contained in that array during object construction.  If it is, then don't write out the office-addin-usage-data file.
- Also fixed some formatting issues
Yo office imports other packages such as office-addin-manifest, which when loaded as part of an import, invoke the following to create a new usageData object:
export const usageDataObject: usageData.OfficeAddinUsageData = new usageData.OfficeAddinUsageData({
projectName: "office-addin-manifest",
instrumentationKey:  usageData.instrumentationKeyForOfficeAddinCLITools,
raisePrompt: …

Address recent drop in usage data because usagelevel set to off

---

packages/office-addin-usage-data/src/usageData.ts

- Customers with port 443 turned off for outgoing traffic, are hitting an AppInsights.Sender error even when usage data is set to "off".  The reason for this is that we still call the setup method method for appInsights, which makes and https call, even if office-addin-usage-data is set to off.
- The fix is to only call the setup method when office-addin-usage-data usageDataLevel is set to true
- I verifed locally that with port 443 blocked for outgoing traffic and usage data set to off, we no longer hit the AppInsignts.Sender error

Fixes issue #290 - Application Insights errors

---

package-lock.json
package.json
packages/custom-functions-metadata-plugin/package-lock.json
packages/custom-functions-metadata/package-lock.json
packages/office-addin-cli/package-lock.json
packages/office-addin-cli/package.json
packages/office-addin-debugging/package-lock.json
packages/office-addin-debugging/package.json
packages/office-addin-dev-certs/package-lock.json
packages/office-addin-dev-settings/package-lock.json
packages/office-addin-lint/package-lock.json
packages/office-addin-manifest/package-lock.json
packages/office-addin-manifest/package.json
packages/office-addin-node-debugger/package-lock.json
packages/office-addin-node-debugger/package.json
packages/office-addin-sso/package-lock.json
packages/office-addin-sso/package.json
packages/office-addin-test-server/package-lock.json
packages/office-addin-usage-data/package-lock.json

This adds scripts so that you can run `npm run audit` and `npm run audit:fix` to use npm to audit and fix all packages. Note that `npm audit` and `npm audit fix` will just do the root lerna package. Take care to use the correct syntax.
This also fixes the existing vulnerabilities.

Fix vulnerabilities

---

packages/office-addin-manifest/src/commands.ts

This allows a project to have a devDependency on this project and add a call to
`office-addin-manifest validate manifest.xml` (e.g. during `npm test`) and check the error code in a test,
so if someone changes the manifest in the project you can get immediate feedback
of a broken manifest.

Exit non zero if manifest is invalid

---

packages/office-addin-dev-certs/README.md

- An internal Microsoft person was running into problems when following our ReadMe instructions for office-addin-dev-certs commands

Typos in dev-certs ReadMe causing people to run incorrect commands

---

packages/custom-functions-metadata/src/generate.ts

Import for default xregexp wasn't working when package was consumed by other project.  This import statement works better.

Update import ref for xregexp

---

packages/office-addin-manifest/test/test.ts

- https://github.com/OfficeDev/generator-office/issues/590 tracks an issue with manifest validation, which I believe is a bug. I have contacted OMEX about the behavior and suggested they fix it. Several customers have also contacted us about this issue so it's becoming a real problem
- Once the issue is fixed, we will re-enable the tests, but for now we should disable these tests because it will cause our CI loops to fail for all other changes made to Office-Addin-Scripts
- I will open a VSO bug to track re-enabling the tests once the validation issue is fixed

Disable manifest validation tests until validation issue fixed

---

packages/office-addin-manifest/package-lock.json
packages/office-addin-manifest/package.json
packages/office-addin-manifest/src/validate.ts

Adds ?gates=DisableIconDimensionValidation to skip the localhost breaking change in our manifest validation service.
Bumps package version to 1.5.13

Add url param for office-addin-manifest to skip icon check in validation service

---

packages/office-addin-dev-settings/README.md
packages/office-addin-dev-settings/src/cli.ts
packages/office-addin-dev-settings/src/commands.ts

The actual code to enable webview switching to Edge Chromium already exists, this just adds the documentation to make it easy for devs to look up.

Add Edge Chromium documentation to Office-Addin-Dev-Settings

---

packages/office-addin-dev-settings/src/commands.ts
packages/office-addin-dev-settings/src/dev-settings-windows.ts
packages/office-addin-dev-settings/src/dev-settings.ts

Display the webview type name when viewing or setting the web view type.
The web view type is set to Microsoft Edge (Chromium).
The web view type is set to legacy Microsoft Edge (EdgeHTML).
The web view type is set to Microsoft Internet Explorer.

webview command: show a better name for the webview type

---

packages/office-addin-dev-settings/src/sideload.ts

- This addresses the scenario where the Outlook exe path that is to be lauched has a space in it.

Fix bug where Outlook exe path has a space in the path

---

packages/office-addin-manifest/src/commands.ts
packages/office-addin-manifest/src/validate.ts
packages/office-addin-manifest/test/test.ts

- Call readManifestFile to ensure manifestPath is valid before calling validateManifest. Catch block will catch error if manifest file path is not a valid file and return error to use (e.g. rror: ENOENT: no such file or directory, open 'C:\Office-Addin-Scripts\packages\office-addin-manifest\foo.xml')
- Fixes issue https://github.com/OfficeDev/Office-Addin-Scripts/issues/352

validate command should throw error if manifest path isn't valid

---

packages/office-addin-debugging/src/start.ts
packages/office-addin-dev-settings/src/commands.ts
packages/office-addin-dev-settings/src/sideload.ts
packages/office-addin-dev-settings/test/unit-tests/test.ts

- Now we can just check is process environment variable WEB_SIDELOAD_TEST is set and if it is we will append the test query param to the end of the sideload url to suppress sideload warning opt-in and warning dialog
- I validated this works in the context of web UI tests I created at https://github.com/TCourtneyOwen/Office-Addin-TaskPane/tree/add-web-tests

Removes isTest param from sideloadAddin

---

packages/office-addin-sso/src/configure.ts

- Azure seems to have recently changed the naming convention for a tenant admin from "Company Administrator" to "Global Administrator" and as a result granting admin consent was failing for the SSO application created via configure-sso
- I believe this should fix https://github.com/OfficeDev/Office-Addin-Taskpane-SSO/issues/25

Fix issue with granting admin consent

---

packages/office-addin-debugging/src/commands.ts
packages/office-addin-debugging/src/start.ts
packages/office-addin-dev-settings/README.md
packages/office-addin-dev-settings/src/cli.ts
packages/office-addin-dev-settings/src/commands.ts
packages/office-addin-dev-settings/src/sideload.ts
packages/office-addin-dev-settings/test/unit-tests/test.ts

Make appType param not required for sideload command
- Update sideload cli to reflect type is once again an option, not required 
- Update sideloadAddin to make appType optional and revert param ordering for method back to previous method signature so this is not a breaking change
- Update Readme to reflect that type is now an option
- Remove check for Outlook sideloading environment variable so we can enable Outlook sideloading (we don't have to include this in this PR but I thought it would be nice to get this enabled soon)
- Incorporate changes from StartDebuggingOptions to fix issue with default options not being set properly. Also remove manifestPath from StartDebuggingOptions as it's not really an option - it's required

Make app type unrequired for sideload

---

packages/office-addin-debugging/src/start.ts

Office-Addin-TaskPane tests will not run because debugging is enabled even though `enableDebugging: false` was specified.
This is because the || operator does not distinguish between undefined and false.

startDebugging() - fix default for enableDebugging

---

packages/office-addin-debugging/src/start.ts

Removed the following code:
// enable debugging
if (isDesktopAppType && isWindowsPlatform) {
await devSettings.enableDebugging(manifestInfo.id, enableDebugging, debuggingMethod, openDevTools);
if (enableDebugging) {
console.log(`Enabled debugging for add-in ${manifestInfo.id}. Debug method: ${DebuggingMethod[debuggingMethod]}`);
}
}

Removing Debug Method console logging

---

package.json

Create "exec" script for running lerna exec.
Update other scripts to use "npm run exec".
Add scripts "install-packages" and "clean-install-packages" which run "npm install" or "npm ci", respectively, and then run "npm install" in the root afterward.

improve npm scripts

---

packages/office-addin-lint/package-lock.json
packages/office-addin-lint/package.json

Updating ```eslint``` versions to update the version of ```lodash``` package used by them.
The ```lodash``` version 4.17.19 has a vulnerability issue and needs to be updated to avoid that.
Tested with:
1. ```npm install```
2. ```npm run build```
3. ```npm run test```
4. Checked that the ```lodash``` version was updated to the latest in package-lock.json

Updating eslint versions for Office-Adding-Lint

---

packages/office-addin-usage-data/src/usageData.ts

Adding functions:
```reportSuccess```
```reportExpectedException```
```reportException```
And deprecating old ones.
Adding ```expectedError``` class.
Tested by calling each function and seeing the results in the logs.

Adding possibility to report expected error

---

packages/office-addin-dev-settings/package-lock.json
packages/office-addin-dev-settings/package.json
packages/office-addin-dev-settings/src/sideload.ts

Checking  the Outlook install version as part of the sideload command to determine if it's a valid version (needs to >= 16.0.13709.10000)
Tested with my computer with the version installed and tested with: 16.0.13628.20346
It successfully throws an ```ExpectedError``` in that case.

Adding outlook version check

---

packages/office-addin-sso/package-lock.json

Using the new office-addin-sso package we published doesn't work saying 'TypeError: defaults_1.usageDataObject.reportSuccess is not a function' . . . using the autogenerated package-lock.json file correct this (at least when locally connecting the two projects).

Lock file update to get newer packages.

---

packages/office-addin-usage-data/package.json

A few publishes ago the version for office-addin-usage-data got changed from 1.1.7 => 1.0.19 which backwards and causes other packages that depend on this to not pickup the changes (since it looks like they have a newer version already).  This will reset the version back forward to correct that.

Correcting usage-data package version number

---

packages/office-addin-lint/config/.eslintrc.json

Create the end of line auto rule to fix the end of line issues in Windows for the template projects.
Tests:
On taskpane project, opened a test PR with this change to see that the lining errors disappeared: [https://github.com/OfficeDev/Office-Addin-TaskPane/pull/108](url)

Adding rule to endOfLine auto

---

packages/office-addin-debugging/src/start.ts

This change is needed to workaround a minor and subtle that is happening when startDebugging is called directly, with this `liveReload` not set. 
The reason for the fix is that the template Excel Custom Functions on the script `npm run test` doesn't properly load the custom functions given this bug.

Making enableLiveReload default to true

---

packages/office-addin-debugging/src/start.ts
packages/office-addin-dev-settings/src/appcontainer.ts
packages/office-addin-dev-settings/src/dev-settings.ts
packages/office-addin-dev-settings/src/sideload.ts
packages/office-addin-manifest/src/addInTypes.ts
packages/office-addin-usage-data/package-lock.json
packages/office-addin-usage-data/package.json
packages/office-addin-usage-data/src/usageData.ts
packages/office-addin-usage-data/test/test.ts

What was done:
- Added some Expected Errors on some errors that were missing.
- Adding better debug message to `Sideload is not supported` error.
- Changing the `maskFilePaths` function to trim absolute files up to extension.
- Before: C:\path\filename.ext would be trimmed to C:\\filename.ext
- Now: C:\path\filename.ext would be trimmed to C:\\.ext
- This needed to be done because sometimes the filename may contain an UID
- Adding more unit tests for this `maskFilePaths` function.

Making File Paths more Strictly

---

packages/eslint-config-office-addins/src/main.ts
packages/eslint-plugin-excel-custom-functions/package-lock.json
packages/eslint-plugin-excel-custom-functions/package.json
packages/eslint-plugin-office-addins/jest.config.js
packages/eslint-plugin-office-addins/package-lock.json
packages/eslint-plugin-office-addins/package.json
packages/eslint-plugin-office-addins/src/main.ts
packages/eslint-plugin-office-addins/src/rules/index.ts
packages/eslint-plugin-office-addins/src/rules/no-context-sync-in-loop.ts
packages/eslint-plugin-office-addins/test/rules/no-context-sync-in-loop.test.ts
packages/eslint-plugin-office-addins/tsconfig.json
packages/office-addin-lint/config/.eslintrc.json
packages/office-addin-lint/package-lock.json

This add the first linter rule and test infrastructure to the plugin.  The rule isn't hooked up to the config so a local change is necessary to enable the rule:  
- add the rule to the list of rules in main.ts of the plugin
- or add the rule to the template eslintrc file
A local change to include the "bad code" is also needed to trigger the rule.
Broader hookup to the linter config will happen when we are ready to "ship" our first set of rules.

Linter prototype rule

---

packages/eslint-plugin-office-addins/src/main.ts
packages/office-addin-lint/config/.eslintrc.test.json
packages/office-addin-lint/src/cli.ts
packages/office-addin-lint/src/commands.ts
packages/office-addin-lint/src/lint.ts
packages/office-addin-lint/test/src/test.ts

Adding another config in eslint-plugin-office-addings and a command argument in office-addin-lint to use it.  This will also us to add rules to the test config and then once they are in then the test project only have to adjust their call to use the test lint config instead of symlinking between the different parts locally (plugin, lint, and template).

Adding test config for office-addin-lint

---

packages/eslint-plugin-excel-custom-functions/package.json
packages/office-addin-prettier-config/package.json

Package **eslint-plugin-excel-custom-functions** was missing these fields.
```
eslint-plugin-excel-custom-functions: npm WARN eslint-plugin-excel-custom-functions@0.0.19 requires a peer of eslint@^7.9.0 but none is installed. You must install peer dependencies yourself.
eslint-plugin-excel-custom-functions: npm WARN eslint-plugin-excel-custom-functions@0.0.19 No repository field.
eslint-plugin-excel-custom-functions: npm WARN eslint-plugin-excel-custom-functions@0.0.19 No license field.
```
Package **office-addin-prettier-config** was missing the repository field.
```
office-addin-prettier-config: npm WARN office-addin-prettier-config@1.0.16 No repository field.
```

Add license, repository and bugs information

---

packages/office-addin-sso/src/server.ts

Display error message when the credential store does not have secret for the current application.
This changes the behavior of the **getSecret** method called by **startSsoService**.
When the application does not have secret stored in the credential store the script will fail without any indication of what is wrong.
**Current behavior**
```
$ npm run start:server
> outlook-sso@0.0.0 start:server C:\dev\Outlook SSO
> office-addin-sso start manifest.xml
(node:35208) UnhandledPromiseRejectionWarning: false
(Use `node --trace-warnings ...` to show where the warning was created)
(node:35208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting 
a promise which was not handled …
```

Error message for credential store

---

packages/eslint-plugin-office-addins/src/rules/no-context-sync-in-loop.ts

It might flag more then desired, but I think it's better then potentially missing a bunch.

Remove requirement to be in run method for no-context-sync-in-loop rule

---

packages/eslint-config-office-addins/package-lock.json
packages/eslint-config-office-addins/package.json
packages/eslint-plugin-excel-custom-functions/package-lock.json
packages/eslint-plugin-excel-custom-functions/package.json
packages/eslint-plugin-office-addins/package-lock.json
packages/eslint-plugin-office-addins/package.json
packages/office-addin-lint/package-lock.json
packages/office-addin-lint/package.json

Previously I switch eslint-plugin-office-addins to use peerdependencies instead of dependencies since that it more technically correct according to documentation.  It seems that something about that switch is not correct since when linking a template project and running office-addin-lint I keep getting errors about packages not being found (even as I tweak the versions references and some other dependency lists).  
Instead of holding up other changes (like the linter rules) while I figure this out, I'm changing back to dependencies so that things work (even if not technically correct).

Use dependencies instead of peers

---

packages/office-addin-sso/src/commands.ts
packages/office-addin-sso/src/configure.ts

We are getting errors when trying to configure the new sso app.  It seems that the app isn't quite ready when try to change it, but there doesn't seem to be a great way to check for app readiness.  Adding some failure retries in order eventually get success.

Switch some command to retry on failure

---

packages/office-addin-lint/src/lint.ts

This will fix the problem with the lint command when projects have a space in the name or path and for the linter running on Mac.

Add quotes around linter command args

---

packages/eslint-plugin-office-addins/package-lock.json
packages/eslint-plugin-office-addins/package.json

Updating packages versions, because beforehand, the following warning would appear when running `npm run lint` command.  The warning goes away after updating those versions.
```
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.3.0
YOUR TYPESCRIPT VERSION: 4.3.5
Please only submit bug reports when using the officially supported version.
=============
```

Updating typescript eslint version

---

packages/eslint-plugin-office-addins/src/rules/call-sync-after-load.ts
packages/eslint-plugin-office-addins/src/rules/load-object-before-read.ts
packages/eslint-plugin-office-addins/src/rules/no-empty-load.ts
packages/eslint-plugin-office-addins/src/rules/no-navigational-load.ts
packages/eslint-plugin-office-addins/src/utils/load.ts
packages/eslint-plugin-office-addins/test/rules/no-empty-load.test.ts
packages/eslint-plugin-office-addins/test/rules/no-navigational-load.test.ts

Fixing the exception that fired when load is empty. The error was being fired on other rules and not on the `emptyLoad` rule, that's why our tests didn't catch the error.

Adding a check to see if load is empty

---

packages/eslint-plugin-office-addins/src/rules/no-navigational-load.ts
packages/eslint-plugin-office-addins/test/rules/no-navigational-load.test.ts

The navigational eslint rule was having a lot of false positives regarding ambiguous properties (that can be navigational or scalar).
I'm putting it so that the rule won't fire a case of ambiguous rules to reduce false positives.

Not reporting errors on ambiguous navigational properties

---

packages/custom-functions-metadata/package-lock.json
packages/custom-functions-metadata/package.json
packages/eslint-config-office-addins/package-lock.json
packages/eslint-config-office-addins/package.json
packages/eslint-plugin-excel-custom-functions/package-lock.json
packages/eslint-plugin-excel-custom-functions/package.json
packages/eslint-plugin-office-addins/package-lock.json
packages/eslint-plugin-office-addins/package.json
packages/office-addin-cli/package-lock.json
packages/office-addin-cli/package.json
packages/office-addin-dev-certs/package-lock.json
packages/office-addin-dev-certs/package.json
packages/office-addin-lint/package-lock.json
packages/office-addin-lint/package.json
packages/office-addin-manifest/package-lock.json
packages/office-addin-manifest/package.json
packages/office-addin-node-debugger/package-lock.json
packages/office-addin-node-debugger/package.json
packages/office-addin-test-helpers/package-lock.json
packages/office-addin-test-helpers/package.json
packages/office-addin-usage-data/package-lock.json
packages/office-addin-usage-data/package.json

Looks like when we only needed to revert the version update for some of the packages and not all of them.  This updates the versions in the repo to match what is published in npm.  The next lerna publish should put things back in complete sync.

Update package version to match npm registry

---

packages/office-addin-debugging/README.md
packages/office-addin-dev-settings/README.md
packages/office-addin-lint/README.md
packages/office-addin-usage-data/README.md

Apparently some of the readme files didn't have the right command name.

Add missing hyphen between "office" and "addin"

---

packages/office-addin-mock/README.md

Just some clean-up on the code inside the mocking readme.

Making mock Readme examples use latest version of API

---

packages/office-addin-mock/src/officeMockObject.ts
packages/office-addin-mock/src/possibleErrors.ts
packages/office-addin-mock/test/officeMockObject.test.ts

Fixing bugs in the office-addin-mock packages.
The first is adding async to the `sync` function.
The second is supporting calls on existing properties in the object model, followed by `sync` or a `load`.
Examples of that are in the new tests added, which are supported (tested in script lab) but wouldn't work with the mock package.

Mock bug fixes

---

packages/office-addin-dev-settings/src/sideload.ts

Making code accepts existing documents for sideloading on desktop.
Fixes in part: https://github.com/OfficeDev/Office-Addin-Scripts/issues/500 and https://github.com/OfficeDev/Office-Addin-Scripts/pull/564
This will make the CLI for `office-addin-debugging` work for documents created using our tooling and referenced later.
This won't fix the problem of making the tool work with any document, because editing them would cause the client to detect a corruption issue.

Sideload desktop existing file

---

packages/office-addin-dev-certs/.gitattributes

Somehow the package coming from npm has the .sh script files with CRLF endings which breaks the scripts.  This should force those files to use LF as their endings.

Force .sh to use LF instead of CRLF

---

packages/office-addin-manifest/src/export.ts

Tests for the manifest export function were flaky because the function did not wait for the zip file to be created.
Fixed it so the code is more consistent.

Making export code await to zip be created

---

packages/office-addin-manifest/.vscode/launch.json
packages/office-addin-manifest/src/cli.ts
packages/office-addin-manifest/src/commands.ts
packages/office-addin-manifest/src/validate.ts
packages/office-addin-manifest/test/test.ts

The OMEX teams has asked that we change from a gate to a url param for indicating our manifest validation comes from a dev environment.  I have also added a command argument that allows the validation to be done for a production environment.

Update validation url

---

packages/office-addin-usage-data/src/usageData.ts
packages/office-addin-usage-data/test/test.ts

The function `maskFilePaths ` was having a side effect of modifying the value passed to it.
This would lead to unwanted behavior in the function `reportExpectedException` for example, in which calling it would have side effects on the parameter.

Removing sideffects from maskFilePaths telemetry function

---

packages/office-addin-mock/src/officeMockObject.ts

Removing deprecated `addMock`, `setMock` and `addMockFunction`. 
A Major update when releasing will be needed.

Removing deprecated mock functions

---

packages/office-addin-manifest/test/test.ts

Looks like the number of errors reported by the validation service (valid change and no change on us is necessary) has changed for production and the test needs to be updated to match.

Update number of prod failure messages reported

---

packages/office-addin-mock/README.md
packages/office-addin-mock/package-lock.json
packages/office-addin-mock/package.json
packages/office-addin-mock/src/host.ts
packages/office-addin-mock/src/objectData.ts
packages/office-addin-mock/src/officeMockObject.ts
packages/office-addin-mock/test/host.test.ts
packages/office-addin-mock/test/officeMockObject.test.ts

Creating an outlook flag to pass to the mocking object in order to bypass the need for a property wait for load and sync calls.
Previous to this commit, a property assigned in the constructor of `OfficeAddinMock` would always require a `load` call, which is not needed for Outlook.
Solves this issue: https://github.com/OfficeDev/Office-Addin-Scripts/issues/587

[Minor] Creating an isOutlook option for the object

---

packages/office-addin-dev-certs/scripts/verify.ps1

Customers have reported an error in the host taskpane saying no valid cert was found, but the tooling says the cert is valid.  We haven't been able to repro this . . . until yesterday when I encountered this.  I as investigated it became clear that my cert was expired at 2:30pm, but office-addin-dev-certs said it was still valid when checking against a time of 12AM on the same day (anything after is considered expired).

Adjust the date used to check cert validity

---

packages/office-addin-dev-certs/src/uninstall.ts
packages/office-addin-dev-certs/src/verify.ts

When there is a space in the path the script fails to get called.  Add quote around script path.

Fix mac dev cert script verify and uninstall

---

packages/custom-functions-metadata-plugin/package-lock.json
packages/custom-functions-metadata-plugin/package.json

---
There are reports of errors when using webpack if there are different versions installed together.  This can happen with custom functions project because of the webpack plugin we depend on and then the template uses webpack as well.  Move webpack to be a peer dependency in custom-functions-metadata-plugin will allow the versions to be the same instead of getting out of sync.  Current versions of npm will install peer dependencies even if they aren't explicitly specified in projects, but will use the version specified in projects when they are. …

[patch] Move webpack to peer dependency

---

packages/office-addin-debugging/src/port.ts

---
When 'npm start' is run we check if the required port is already being used (bound to) and assume the dev server is already running if it is.  However it turns out that when an add-in is run in the host a whole bunch of port bindings to the same port are made and when the host is closed some of those bindings linger attached to pid 0 (the idle process) before finally getting cleaned up.  This has the effect of blocking 'npm start' while these bindings are waiting to be cleaned up.  It seems safe to ignore these bindings on pid 0 and allow 'npm start' to re-setup the dev …

[patch] Improve dev server startup

---

packages/office-addin-mock/src/officeMockObject.ts
packages/office-addin-mock/test/officeMockObject.test.ts

**Description**:
Currently OfficeMockObject has no support for dates. It would treat a Date as an object to traverse, adding a OfficeMockObject in place of the date.
I found this issue while working in a Outlook add-in, trying to stub a date in `context.mailbox.item.dateTimeCreated`
```
It has no impacts.
```
```
It has no impacts.
```
I have added a unit test to …

Fix OfficeMockObject not supporting dates. [patch] 

---

packages/eslint-plugin-office-addins/src/rules/load-object-before-read.ts
packages/eslint-plugin-office-addins/test/rules/load-object-before-read.test.ts

---
A customer pointed out that the *OrNullObject calls don't require a "load()" call, but we are flagging them as needing it in our linter rules (https://github.com/OfficeDev/Office-Addin-Scripts/issues/671).  The removes those methods from the checking and adds a test to verify
No.
2. **Do these changes impact *documentation*?** (e.g., a tutorial on https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-a …

Don't flag *OrNullObject as needing load calls

---

packages/office-addin-manifest/src/export.ts

---
Icons without a path weren't being zipped correctly.  Add a case to check for that and zip file w/out dir.
No.
No. …

[patch] Check for icon file path before zipping

---

packages/office-addin-project/src/convert.ts

Deleting the `.xml` manifest after the main conversion is done.
---
Testing conversion of the project and notice the `.xml` manifest is removed even if is not in the root of …

[Patch] Deleting old .xml manifest

---

packages/office-addin-manifest/src/manifestHandler/manifestHandlerJson.ts

---
Fix bug with trying to parse a json manifest that doesn't have an optional array property by using optional chaining check.
No
No …

[patch] Add optional chaining to manifest array objects.

---

.azure-devops/steps/devcerts.yml
packages/custom-functions-metadata-plugin/package-lock.json
packages/custom-functions-metadata-plugin/package.json
packages/custom-functions-metadata-plugin/src/loader.ts

---
Previous vulnerability fix for loader-utils broke usages of the custom functions plugin because of a breaking version change.  Turns out with webpack 5 the use of loader-utils is no longer needed.  Removing the dependency.  Also have a fix for the build piple.
No.
No.
If …

Fix cf plugin

---

packages/office-addin-project/src/convert.ts

---
The code to convert a project from xml manifest to json manifest deletes the xml manifest at the end, but webpack.config is still trying to copy it during debugging, and this throws an error.  This will do a simple fix to webpack.config to change the copy to do the json manifest instead.  A better fix would be to remove that part of the webpack config, but that is far more complex and we need a simple solution now. …

[patch] Fix project convert to update webpack

---

packages/office-addin-dev-certs/src/cli.ts
packages/office-addin-dev-certs/src/commands.ts
packages/office-addin-dev-certs/src/generate.ts
packages/office-addin-dev-certs/src/install.ts

This adds --domains as an option to the office-addin-dev-certs install command.
This allows the set of domains to be customized if needed. By default, the domains are "127.0.0.1" and "localhost".
An example where customization is useful is if "localhost" is not allowed as a domain name. You can map a different name to the local port, but the SSL certificate needs to have that name listed.
For example, on Windows, the hosts file can map "dev-host" to 127.0.0.1 (IPv4) and ::1 (IPv6) by adding these lines to %systemroot%\system32\drivers\etc\hosts:
127.0.0.1 	dev-host
::1		dev-host
Then, use the --domains option to specify the IP addresses and host names:
office-addin-dev-certs install --domains 127.0.0.1,::1,localhost,dev-host
Opening the browser to https://dev-host will show that the SSL …

[minor] office-addin-dev-certs: add --domains option to install

---

packages/office-addin-dev-settings/src/cli.ts
packages/office-addin-dev-settings/src/commands.ts
packages/office-addin-dev-settings/src/dev-settings-windows.ts
packages/office-addin-dev-settings/src/dev-settings.ts
packages/office-addin-dev-settings/src/sideload.ts

---
There will be times when we want to debug a json manifest project that has already been registered.  To allow for this I've refactored the code to separate add-in registration from host loading, updated the registry key that is used by outlook to determine sideloading, and added an argument that indicates the id of an existing registration.  When this is integrated into other tooling they will be able to provide the existing registration id and use our tooling to start localhost and the add-in host. 
1. **Do these changes impact *command syntax* of any of the packages?** …

[minor] Allow for sideloading an existing json registration

---

packages/office-addin-dev-certs/scripts/install.ps1
packages/office-addin-dev-certs/scripts/uninstall.ps1
packages/office-addin-dev-certs/scripts/verify.ps1
packages/office-addin-dev-certs/src/uninstall.ts
packages/office-addin-dev-certs/src/verify.ts

Change Description:
Let's start with robustness issues: no error handling was implemented in powershell scripts. There are executed through execSync, which throws if the error code is not 0. We want execSync to fail if the script fails. See
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.3#erroractionpreference
CA certificate validation was only checking expiration date, which is not enough to prevent dev environment corruption (certificate mismatch, duplication, ...). The following checkings have been added:
- CA certificate in store must match ca.crt
- This certificate must match the issuer of localhost.crt
There was also an issue in clean-up logic. Both verify and uninstall are relying on …

Fixed powershell compatibility and robustness issues

---

packages/office-addin-dev-certs/src/install.ts

This is a fix for issue #718 that works on OSX. It should still be fixed for Linux, but I'm not able currently to test it thoroughly.
No impact on the command syntax, but it will make the `use-machine` flag more effective.
Probably, it should be now described that `use-machine` will impact the certificates installed, not sure though.
Tested on dummy local repository and on actual add-in I'm working on currently.

fixes 718 for OSX

---

packages/office-addin-manifest/src/commands.ts
packages/office-addin-manifest/src/validate.ts

---
If the validation endpoint is unreachable (status other then 200) then we error with a json parsing error which is confusing to customers.  This will capture the status and message, not throw on a json parsing error, and then log the error to the customer to say the site is unreachable.
No.
2. **Do these changes impact *documentation*?** (e.g., a tutorial on …

[minor] Fix validate endpoint error message when site is down

---

packages/office-addin-project/src/commands.ts
packages/office-addin-project/src/convert.ts

---
The project conversion prompt code is part of the convert method which makes this incompatible with calling directly from another module (which is going to happen shortly).  It should really be part of cli command method instead. 
No.
No.
If you answered yes to any of …

[minor] Move confirmation prompt to command level

---

packages/office-addin-mock/src/officeMockObject.ts
packages/office-addin-mock/test/officeMockObject.test.ts

---
The mock doesn't handle calls to the load method that doesn't have any arguments.  This should be the same as a call to load with a "*" as an argument.
No.
No.
> Make sure …

[patch] Fix mock empty load

---

package-lock.json
packages/office-addin-manifest/src/export.ts
packages/office-addin-manifest/test/manifests/manifest.local.json
packages/office-addin-manifest/test/test.ts

---
The export of a json manifest to a zip file was preserving the file name, but it turns out the service we send it to always expects "manifest.json" so changing the zip file creation to rename the manifest to "manifest.json".
No.
No.
If you answered yes to any of these …

[minor] Update name of manifest file in zip to always be "manifest.json"

---

packages/office-addin-debugging/package-lock.json
packages/office-addin-debugging/package.json
packages/office-addin-debugging/src/start.ts
packages/office-addin-manifest/src/export.ts
packages/office-addin-manifest/test/manifests/devPreviewManifest.json
packages/office-addin-manifest/test/manifests/manifest.json
packages/office-addin-manifest/test/manifests/manifest.local.json
packages/office-addin-manifest/test/test.ts

---
In the toolkit the manifest is generated into a build location that add-ins can they use for setting up debugging.  However, the required images are not part of the manifest output of the toolkit.  In order to work with toolkit manifest handling, we need to be able to process receiving a zip file (which contains the manifest and the related required images) for the manifest path.  We extract this so we can get at the manifest information and then re-zip it using icon references that are relative to the manifest location rather than the working directory of the debugging …

[Minor] Handle zipped manifests

---

packages/office-addin-dev-settings/package-lock.json
packages/office-addin-dev-settings/package.json
packages/office-addin-dev-settings/src/sideload.ts

---
For devpreview in May 2022 we added temporary code to convert json manifests back to xml so they could be sideloaded for testing.  This is no longer needed as support for sideloading json manifests is coming.  This is a breaking change for anyone trying to use json manifests with an older version of Outlook that doesn't support json manifests.
No.
2. **Do these changes impact *documentation*?** (e.g., a tutorial on …

[Major] Remove json2xml convert

---

packages/office-addin-project/package-lock.json
packages/office-addin-project/package.json
packages/office-addin-project/src/commands.ts
packages/office-addin-project/test/test-package.json
packages/office-addin-project/test/test.ts

---
Update the version of office-addin-manifest-converter being used by office-addin-project.  Also improved the project convert warning message and update the tests not to output to the project directory.
No.
No.
> …

[Patch] Update manifest converter

---

packages/eslint-plugin-office-addins/src/rules/call-sync-after-load.ts
packages/eslint-plugin-office-addins/src/rules/call-sync-before-read.ts
packages/eslint-plugin-office-addins/src/rules/load-object-before-read.ts
packages/eslint-plugin-office-addins/src/rules/no-navigational-load.ts
packages/eslint-plugin-office-addins/src/rules/test-for-null-using-isNullObject.ts
packages/eslint-plugin-office-addins/src/utils/load.ts
packages/eslint-plugin-office-addins/src/utils/utils.ts
packages/eslint-plugin-office-addins/test/rules/call-sync-after-load.test.ts
packages/eslint-plugin-office-addins/test/rules/load-object-before-read.test.ts
packages/eslint-plugin-office-addins/test/rules/no-navigational-load.test.ts
packages/office-addin-dev-settings/package-lock.json

---
A customer reported that the call to context.load(<obj>, <property>) was not being used by the linter rules to recognize that a load for an object had been called.  This change adds that case when detecting load calls and, in the process, refactor a few other things to try and make the rule more readable.  There are 3 rules that take into account the new load recognition and test cases added for those.
No.
2. **Do …

[minor] Add context.load(...) linter case

---

packages/office-addin-dev-settings/src/dev-settings-mac.ts

---
The check for xml vs. json manifest registration detection on mac machines were always indicating json manifest.  Needed to update conditional statements (and substring extraction) to look for just the extension
No.
No.
If you answered yes to any of these please do the …

[patch] Update json manifest registration check

---

packages/office-addin-project/package-lock.json
packages/office-addin-project/src/convert.ts

---
Change the call to the manifest convert library to use "true" for preserving URLs. (and updated package version in lock file)
No.
No. …

[patch] Change project convert to keep image urls

---

packages/office-addin-project/package-lock.json
packages/office-addin-project/package.json

---
Update office-addin-manifest-convert package which has a fix for the icon references in manifest.json
No.
Maybe . . . get's rid of the workaround needed for the icon file references.
> Include 'Rick-Kirkham' in the …

[patch] Move to office-addin-manifest-converter 0.2.2

---

packages/office-addin-dev-certs/scripts/verify.ps1

Previously, it could be expired for up to 2 days but still verify.
No
No
I can now run my addin from vscode and not see
but now I just see blank and it's stuck saying "We're loading the add-ins run time" Not sure if it's related or not.

[patch] Fix dev-certs verify.ps1

---

packages/custom-functions-metadata-plugin/package-lock.json
packages/custom-functions-metadata-plugin/package.json
packages/custom-functions-metadata-plugin/src/customfunctionsplugin.ts
packages/custom-functions-metadata-plugin/src/loader.ts

---
Update custom functions plugin to take in multiple files as input to pass to the metadata generator.
No.
Maybe . . . the webpack config file will now allow for an array of strings in the plugin configuration.  Not sure if this plugin is referenced anywhere in our …

Cf plugin multiple function files

---

packages/office-addin-dev-certs/scripts/verify.ps1
packages/office-addin-dev-certs/src/verify.ts
packages/office-addin-dev-certs/test/test.ts

The Root CA certificate wasn't properly installed when running `npm start`, turns out the installation was skipped because the code interpreted PowerShell output from my profile as a successful check for an installed certificate.
The change: A PowerShell command might generate initial output (in my case it was some information echo'd in my profile) - this broke the check since the code assumes the cert exists if *any content* is returned. The code now only returns true if the name of the certificate is contained in the returned output:
```bash
Subject      : O=Developer CA for Microsoft Office Add-ins, L=Redmond, S=WA, C=US, CN=Developer CA for Microsoft
Office Add-ins
```
The code matches the **`O=Developer CA for Microsoft Office Add-ins,`** part.
1. **Do these changes impact *command …

[patch] Prevent false positive in Root CA certificate check by ignoring extraneous PowerShell output

---

packages/office-addin-debugging/src/port.ts

In Windows, `npm start` often fails to start the dev server, logging `The dev server is already running on port 3000`, even though it's been stopped with `npm stop` before.  Only the first `npm stop` call shows that it found a process id to stop, so the server is indeed being stopped correctly.
The issue is caused by `getProcessIdsForPort()` often returning `[ 0 ]` and interpreting it as _there's a pid so the server is still running_, since the line being parsed contains a trailing "\r" which breaks the check `!== '0'` in https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/office-addin-debugging/src/port.ts#L78
```ts
if (processId !== undefined && processId !== '0') {
```
Logging the parts being parsed in [`getProcessIdsForPort()`](https://github.com/OfficeDev/Office-Add …

[patch] Ignore trailing \r in parsed processId

---

packages/office-addin-project/package-lock.json
packages/office-addin-project/package.json

---
Update the version of office-addin-manifest-converter (for converting xml => json) that we depend on (which includes a P0 bug fix)
No.
No. …

[patch] Update version of manifest converter package dependency

---

packages/office-addin-dev-certs/scripts/install_linux.sh
packages/office-addin-dev-certs/scripts/uninstall_linux.sh
packages/office-addin-dev-certs/scripts/verify_linux.sh
packages/office-addin-dev-certs/src/install.ts
packages/office-addin-dev-certs/src/uninstall.ts
packages/office-addin-dev-certs/src/verify.ts

I did put it as minor, however I have not tested changes on Ubuntu. Hopefully someone else can test, but I will have access to Ubuntu machine in a few days, I can do the tests.
`npm run dev-server` or `npm run start:web` are affected, it now works on Arch Linux properly.
no
I tested on Arch running `npm run dev-server` and `npm run start:web`, it properly verifies and installs the certificate and changes are propagated to Сhromium. …

[minor] Add Arch Linux support to certificate installation

---

packages/office-addin-dev-settings/package-lock.json
packages/office-addin-dev-settings/package.json
packages/office-addin-dev-settings/src/cli.ts
packages/office-addin-dev-settings/src/dev-settings-windows.ts
packages/office-addin-dev-settings/src/publish.ts
packages/office-addin-dev-settings/test/unit-tests/test.ts

Changing the sideloading of xml manifests to match that of json manifests.  They will both be loaded through the service using teamsfx-cli
No.
No.
Ran automated tests.  Tried sideloading a test project using the script changes targeting current versions of Outlook as well as older ones that don't …

[minor] Use teamsfx-cli to sideload xml manifest

---

packages/office-addin-dev-settings/src/dev-settings-mac.ts
packages/office-addin-dev-settings/src/dev-settings-windows.ts
packages/office-addin-dev-settings/src/publish.ts

---
For the json manifest scenario, removing the cache modification call that were added as a workaround and replace it with setting a registry key that will signal to the host app that a refresh of add-ins is needed.  This will work for both sideloading and unacquiring.
No.
No. …

[minor] Add method for setting a "RefreshAddins" registry key.

---

packages/office-addin-dev-settings/package-lock.json
packages/office-addin-dev-settings/package.json
packages/office-addin-dev-settings/src/publish.ts

---
Fix two bugs:
- teamsfx-cli command needed to quote the manifest path
- The new version of winreg has a bug in it when values contain spaces
No.
No.
> Make sure the README file …

[patch] Fix sideload bugs with path (spaces) and registery (dependency flaw)

---

packages/office-addin-dev-certs/src/uninstall.ts
packages/office-addin-dev-certs/src/verify.ts

Fixes a bug with office-addin-dev-certs on Linux. The verify command always thought the cert was not installed, causing every run of a generic sample app to generate and install new certificates. This was frustrating when trying to debug certificate issues when running a sample app for the first time.

[minor] Fix 'uninstall' and 'verify' for Linux platform in office-addin-dev-certs package.

---

packages/office-addin-sso/src/configure.ts

Microsoft Azure CLI (32-bit) and similar strings will no longer match the check. Modified to check for the substring instead.
This is a patch.
Needs someone to double-check testing that this works correctly when Azure CLI is installed, and when it is uninstalled.

Fix check for Microsoft Azure CLI substring

---

packages/office-addin-sso/src/scripts/getInstalledApps.ps1

getInstalledApps.ps1 should look up the installed apps from 32-bit and 64-bit registry path.
No
No
The script is validated with its consumer, isAzureCliInstalled() defined configure.ts

[Patch] Fix getInstalledApps.ps1 so it can get correct installed apps

---

packages/custom-functions-metadata-plugin/package.json
packages/custom-functions-metadata/package.json
packages/custom-functions-metadata/src/generate.ts
packages/custom-functions-metadata/test/cases/basic/expected.json
packages/custom-functions-metadata/test/cases/cancelable-invocation/expected.json
packages/custom-functions-metadata/test/cases/cancelable/expected.json
packages/custom-functions-metadata/test/cases/default-parameter-types/expected.json
packages/custom-functions-metadata/test/cases/description/expected.json
packages/custom-functions-metadata/test/cases/dimensionality-matrix/expected.json
packages/custom-functions-metadata/test/cases/helpurl/expected.json
packages/custom-functions-metadata/test/cases/invocation/expected.json
packages/custom-functions-metadata/test/cases/js-function-name-lowercase/expected.json
packages/custom-functions-metadata/test/cases/js-function-name-mixed-case/expected.json
packages/custom-functions-metadata/test/cases/js-function-name-uppercase/expected.json
packages/custom-functions-metadata/test/cases/multiple-function-files/expected.json
packages/custom-functions-metadata/test/cases/optional-parameter-types/expected.json
packages/custom-functions-metadata/test/cases/param-types/expected.json
packages/custom-functions-metadata/test/cases/repeating-param-1d-reference/expected.json
packages/custom-functions-metadata/test/cases/repeating-param-1d/expected.json
packages/custom-functions-metadata/test/cases/repeating-param-3d-reference/expected.json
packages/custom-functions-metadata/test/cases/repeating-param-3d/expected.json
packages/custom-functions-metadata/test/cases/requiresaddress-cancelable/expected.json
packages/custom-functions-metadata/test/cases/requiresaddress/expected.json
packages/custom-functions-metadata/test/cases/requiresparameteraddresses/expected.json
packages/custom-functions-metadata/test/cases/return-type-explicit/expected.json
packages/custom-functions-metadata/test/cases/return-type-implicit/expected.json
packages/custom-functions-metadata/test/cases/streaming-invocation-dimensionality-matrix/expected.json
packages/custom-functions-metadata/test/cases/streaming-invocation-dimensionality-scalar/expected.json
packages/custom-functions-metadata/test/cases/streaming-invocation/expected.json
packages/custom-functions-metadata/test/cases/streaming/expected.json

Custom function metadata generation now adds `allowCustomDataForDataTypeAny:true` by default to functions.json.
1. **Do these changes impact *command syntax* of any of the packages?** 
No
2. **Do these changes impact *documentation*?**
On page [Use data types with custom functions in Excel](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-data-types-concepts), it is mentioned that "To use the data types integration with custom functions, the custom functions JSON metadata file must be manually updated to include the property allowCustomDataForDataTypeAny. Set this property to true.". This paragraph can be removed since manually adding allowCustomDataForDataTypeAny is no longer needed.
npm run test passes

[Patch] Set allowCustomDataForDataTypeAny to true by default for custom function metadata generation

---

packages/custom-functions-metadata/Specification.md
packages/custom-functions-metadata/package-lock.json
packages/custom-functions-metadata/src/parseTree.ts
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-excludefromautocomplete/expected.js.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-excludefromautocomplete/expected.ts.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-excludefromautocomplete/functions.js
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-excludefromautocomplete/functions.ts
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-streaming/expected.js.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-streaming/expected.ts.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-streaming/functions.js
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-streaming/functions.ts
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-volatile/expected.js.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-volatile/expected.ts.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-volatile/functions.js
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-volatile/functions.ts
packages/custom-functions-metadata/test/cases/excludefromautocomplete/expected.json
packages/custom-functions-metadata/test/cases/excludefromautocomplete/functions.js
packages/custom-functions-metadata/test/cases/excludefromautocomplete/functions.ts
packages/custom-functions-metadata/test/cases/linkedentitydataprovider/expected.json
packages/custom-functions-metadata/test/cases/linkedentitydataprovider/functions.js
packages/custom-functions-metadata/test/cases/linkedentitydataprovider/functions.ts

This PR adds handling for the new @linkedEntityDataProvider and @excludeFromAutoComplete metadata tags needed for 3P Linked Entities in Excel.
Yes, we need to add documentation for the new tags
Wrote new test cases and confirmed they all pass. Will link NPM package to office-js-api to test everything before checking in.

[minor] Add handling for new @linkedEntityDataProvider and @excludeFromAutoComplete jsdoc tags

---

packages/office-addin-dev-settings/src/dev-settings-windows.ts
packages/office-addin-dev-settings/src/sideload.ts
packages/office-addin-manifest/src/manifestHandler/manifestHandlerJson.ts
packages/office-addin-manifest/src/manifestHandler/manifestHandlerXml.ts
packages/office-addin-manifest/src/manifestInfo.ts
packages/office-addin-manifest/test/test.ts

When the manifest is WXP JSON, the following changes are made:
- Switch to TAOS sideload option.
- Launch host directly.

[minor] Add TAOS sideload support for MetaOS WXP

---

packages/office-addin-debugging/src/start.ts

This PR fix the issue when add loopback exemption failed, the debug start process will totally break.\
The behavior will be the same as when user type `No` for add loopback exempt question.
Detail in this [issue 840](https://github.com/OfficeDev/Office-Addin-Scripts/issues/840)
1. **Do these changes impact *command syntax* of any of the packages?** 
No.
2. **Do these changes impact *documentation*?**
Maybe No.
I search the docs and found the following articles:
* [Manually sideload an add-in to Office on the web](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing#manually-sideload-an-add-in-to-office-on-the-web)
* [Start the Excel, PowerPoint, or Word add-in project](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/debug-office-add- …

[patch] Fix when add loopback exemption failed will break the debug process

---

.npmrc
packages/office-addin-dev-settings/package-lock.json
packages/office-addin-lint/.vscode/launch.json
packages/office-addin-lint/package-lock.json
packages/office-addin-lint/package.json
packages/office-addin-lint/src/lint.ts
packages/office-addin-lint/tsconfig.json

Update the package versions for office-addin-lint.
For context, I was working on a project derived from Office-Addin-TaskPane-React template which involves custom functions, and was running into strange errors from eslint in TypeScript code in VS Code. I noticed that eslint was very out of date. After updating these package versions, building Office-Addin-Scripts and linking to office-addin-lint from the project, it fixed the errors.
NOTE: I removed engines-strict in .npmrc so I could use Node LTS. 
I always wanted to mention that I think there should be a process to regularly update packages to newer versions across the repository. Relying only on dependabot or making updates only for addressing vulnerabilities isn't really enough. It's better to stay current with TypeScript, eslint, …

[minor] office-addin-lint: update package versions

---

packages/eslint-plugin-office-addins/package-lock.json
packages/eslint-plugin-office-addins/package.json
packages/eslint-plugin-office-addins/src/rules/call-sync-after-load.ts
packages/eslint-plugin-office-addins/src/rules/call-sync-before-read.ts
packages/eslint-plugin-office-addins/src/rules/load-object-before-read.ts
packages/eslint-plugin-office-addins/src/rules/no-context-sync-in-loop.ts
packages/eslint-plugin-office-addins/src/rules/no-empty-load.ts
packages/eslint-plugin-office-addins/src/rules/no-navigational-load.ts
packages/eslint-plugin-office-addins/src/rules/no-office-initialize.ts
packages/eslint-plugin-office-addins/src/rules/test-for-null-using-isNullObject.ts
packages/eslint-plugin-office-addins/src/utils/load.ts
packages/eslint-plugin-office-addins/src/utils/utils.ts
packages/eslint-plugin-office-addins/test/rules/call-sync-after-load.test.ts
packages/eslint-plugin-office-addins/test/rules/call-sync-before-read.test.ts
packages/eslint-plugin-office-addins/test/rules/load-object-before-read.test.ts
packages/eslint-plugin-office-addins/test/rules/no-context-sync-in-loop.test.ts
packages/eslint-plugin-office-addins/test/rules/no-empty-load.test.ts
packages/eslint-plugin-office-addins/test/rules/no-navigational-load.test.ts
packages/eslint-plugin-office-addins/test/rules/no-office-initialize.test.ts
packages/eslint-plugin-office-addins/test/rules/test-for-null-using-isNullObject.test.ts
packages/eslint-plugin-office-addins/tsconfig.json

---
Projects that use typescript 5 will show a warning when running our linter that certain libraries are not compatible with typescript 5.  One of those cases is the custom linter rules where we see package dependencies getting a little stale.  This will update all of those dependencies and then make matching code changes for those major version updates.
No.
2. **Do these changes impact *documentation*?** (e.g., a …

[Major] Update packages in eslint-plugin-office-addins for updated typescript support

---

packages/office-addin-project/package-lock.json
packages/office-addin-project/package.json

---
Update office-addin-manifest-converter version to get bug fix for schema reference
No.
No.
ran automated …

Update manifest convert to 3.1 (bug fix needed)

---

packages/office-addin-sso/package-lock.json
packages/office-addin-sso/package.json

Upgrades the `express` npm package in office-addin-sso to the latest version (4.19.2) to fix the following vulnerability:
1. **Do these changes impact *command syntax* of any of the packages?** No
2. **Do these changes impact *documentation*?** No
**Validation/testing performed**: Not sure how to manually test this in my add in

[patch] upgrade express package in office-addin-sso to fix security vulnerability

---

packages/office-addin-mock/src/officeMockObject.ts
packages/office-addin-mock/test/officeMockObject.test.ts

Aligns return value for `load` with that used in production (i.e., return the object).
No.
No.
Wrote a test. Tested manually

[patch] Return object from calls to load()

---

packages/office-addin-prettier-config/prettier.config.js
packages/office-addin-sso/package.json

---
When updating the eslint and prettier plugin versions a rule was changed to require trailing commas.  We need to be compatible with older "es" version so setting the prettier config to that.  Also move a dependency to lint to the dev section in another package
No.
No.
If you …

[patch] Update config to use es5 trailing comma rule and move dependency to dev

---

packages/office-addin-debugging/package-lock.json
packages/office-addin-debugging/package.json
packages/office-addin-dev-settings/package-lock.json
packages/office-addin-dev-settings/package.json
packages/office-addin-manifest/package-lock.json
packages/office-addin-manifest/package.json
packages/office-addin-project/package-lock.json
packages/office-addin-project/package.json

---
adm-zip is used in a few places to create and read zip files.  It turns out recent changes to adm-zip have a bug tail that is affecting sideloading json manifest zip files.  This change standardizes all packages to the same adm-zip version that is not experiencing the problems.
No.
2. **Do these changes impact *documentation*?** (e.g., a tutorial on https://learn.microsoft.com/office/dev/add-ins/overview/office-add- …

[patch] Standardize the version of adm-zip being used.

---

packages/office-addin-project/package-lock.json
packages/office-addin-project/package.json
packages/office-addin-project/src/cli.ts
packages/office-addin-project/src/commands.ts
packages/office-addin-project/src/convert.ts

---
Update the version of the package of office-addin-manifest-converter in office-addin-package and then add a "--preview-manifest-schema" option that uses a the devPreview json manifest schema
Yes . . . adds a parameter to office-addin-project that allows the use of the devPreview json manifest schema
2. **Do these changes impact *documentation*?** (e.g., a tutorial on …

Update office-addin-manifest-converter converter package

---

packages/office-addin-dev-certs/src/httpsServerOptions.ts

I want sign a cert for local ip, e.g. 127.1.1.1 \ 192.0.0.0, but getHttpsServerOptions can't pass the domains.
the function `getHttpsServerOptions` add three optional params, they are same as the function `ensureCertificatesAreInstalled` 's params.
> Make sure the README file is …

[patch] getHttpsServerOptions add params

---

packages/custom-functions-metadata/Specification.md
packages/custom-functions-metadata/package-lock.json
packages/custom-functions-metadata/src/parseTree.ts
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-capturesCallingObject/expected.js.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-capturesCallingObject/expected.ts.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-capturesCallingObject/functions.js
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-capturesCallingObject/functions.ts
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-excludefromautocomplete/expected.js.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-excludefromautocomplete/expected.ts.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-excludefromautocomplete/functions.js
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-excludefromautocomplete/functions.ts
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-requiresaddress/expected.js.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-requiresaddress/expected.ts.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-requiresaddress/functions.js
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-requiresaddress/functions.ts
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-requiresparameteraddresses/expected.js.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-requiresparameteraddresses/expected.ts.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-requiresparameteraddresses/functions.js
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-requiresparameteraddresses/functions.ts
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-streaming/expected.js.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-streaming/expected.ts.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-streaming/functions.js
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-streaming/functions.ts
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-volatile/expected.js.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-volatile/expected.ts.errors.txt
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-volatile/functions.js
packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-volatile/functions.ts
packages/custom-functions-metadata/test/cases/linkedentitydataprovider/expected.json
packages/custom-functions-metadata/test/cases/linkedentitydataprovider/functions.js
packages/custom-functions-metadata/test/cases/linkedentitydataprovider/functions.ts

Updating naming of @linkedEntityDataProvider to @linkedEntityLoadService
No
No

[patch] Add custom function metadata auto-gen support for @linkedEntityLoadService

---

packages/office-addin-sso/package-lock.json
packages/office-addin-sso/package.json

This change upgrades the path-to-regexp package to version 0.1.12 (to address vulnerabilities).
No
No
Validated with `npm run test`.

[patch] Upgrade path-to-regexp to 0.1.12
